var impact_factors={
"ca-a cancer journal for clinicians":503.1,
"nature reviews drug discovery":122.7,
"lancet":98.4,
"new england journal of medicine":96.2,
"bmj-british medical journal":93.6,
"nature reviews molecular cell biology":81.3,
"nature reviews clinical oncology":81.1,
"nature reviews materials":79.8,
"nature reviews disease primers":76.9,
"nature reviews cancer":72.5,
"nature reviews microbiology":69.2,
"nature reviews immunology":67.7,
"foundations and trends in machine learning":65.3,
"jama-journal of the american medical association":63.1,
"world psychiatry":60.5,
"nature medicine":58.7,
"annals of oncology":56.7,
"chemical reviews":51.4,
"nature":50.5,
"nature reviews methods primers":50.1,
"nature energy":49.7,
"nature reviews earth & environment":49.7,
"cancer cell":48.8,
"lancet neurology":46.5,
"nature reviews gastroenterology & hepatology":45.9,
"reviews of modern physics":45.9,
"cell":45.5,
"nature reviews physics":44.8,
"science":44.7,
"lancet diabetes & endocrinology":44,
"escience":42.9,
"nature catalysis":42.8,
"journal of clinical oncology":42.1,
"nature reviews cardiology":41.7,
"lancet oncology":41.6,
"signal transduction and targeted therapy":40.8,
"chemical society reviews":40.4,
"nature reviews genetics":39.1,
"lancet respiratory medicine":38.7,
"joule":38.6,
"nature nanotechnology":38.1,
"nature reviews chemistry":38.1,
"european heart journal":37.6,
"mmwr surveillance summaries":37.3,
"nature materials":37.2,
"lancet infectious diseases":36.4,
"nature methods":36.1,
"circulation":35.5,
"advances in physics":35,
"ieee communications surveys and tutorials":34.4,
"nature electronics":33.7,
"progress in materials science":33.6,
"innovation":33.2,
"nature biotechnology":33.1,
"energy & environmental science":32.4,
"nature photonics":32.3,
"progress in energy and combustion science":32,
"nature genetics":31.7,
"nano-micro letters":31.6,
"materials science & engineering r-reports":31.6,
"nature reviews endocrinology":31,
"lancet gastroenterology & hepatology":30.9,
"lancet psychiatry":30.8,
"physiological reviews":29.9,
"cancer discovery":29.7,
"nature climate change":29.6,
"journal of hematology & oncology":29.5,
"nature reviews rheumatology":29.4,
"nature reviews neuroscience":28.7,
"advanced powder materials":28.6,
"nature reviews nephrology":28.6,
"annual review of pathology-mechanisms of disease":28.4,
"electrochemical energy reviews":28.4,
"nature reviews neurology":28.2,
"cell research":28.1,
"astronomy and astrophysics review":27.8,
"cell metabolism":27.7,
"molecular cancer":27.7,
"nature immunology":27.7,
"advanced materials":27.4,
"elight":27.2,
"intensive care medicine":27.1,
"annual review of immunology":26.9,
"journal of hepatology":26.8,
"nature biomedical engineering":26.8,
"living reviews in relativity":26.3,
"annual review of astronomy and astrophysics":26.3,
"science robotics":26.1,
"progress in polymer science":26,
"gastroenterology":25.7,
"nature sustainability":25.7,
"immunity":25.5,
"lancet public health":25.4,
"mmwr-morbidity and mortality weekly report":25.4,
"annual review of fluid mechanics":25.4,
"european urology":25.3,
"reviews of geophysics":25.2,
"advances in optics and photonics":25.2,
"jama pediatrics":24.7,
"fungal diversity":24.5,
"interdisciplinary materials":24.5,
"advanced energy materials":24.4,
"lancet planetary health":24.1,
"physics reports-review section of physics letters":23.9,
"lancet digital health":23.8,
"acm computing surveys":23.8,
"imeta":23.7,
"annual review of psychology":23.6,
"nature food":23.6,
"nature cancer":23.5,
"proceedings of the ieee":23.2,
"advanced composites and hybrid materials":23.2,
"gut":23,
"living reviews in solar physics":23,
"infomat":22.7,
"jama internal medicine":22.5,
"jama oncology":22.5,
"jama psychiatry":22.5,
"energychem":22.2,
"endocrine reviews":22,
"cellular & molecular immunology":21.8,
"journal of the american college of cardiology":21.7,
"nature human behaviour":21.4,
"annual review of public health":21.4,
"annual review of plant biology":21.3,
"nature neuroscience":21.2,
"materials today":21.1,
"journal of thoracic oncology":21,
"blood":21,
"lancet microbe":20.9,
"ieee transactions on pattern analysis and machine intelligence":20.8,
"cell host & microbe":20.6,
"light-science & applications":20.6,
"advanced photonics":20.6,
"nature microbiology":20.5,
"jama neurology":20.4,
"annals of the rheumatic diseases":20.3,
"coordination chemistry reviews":20.3,
"journal of bioresources and bioproducts":20.2,
"applied catalysis b-environment and energy":20.2,
"international journal of information management":20.1,
"cancer communications":20.1,
"lancet child & adolescent health":19.9,
"lancet global health":19.9,
"cell stem cell":19.8,
"annals of internal medicine":19.6,
"carbon energy":19.5,
"american journal of respiratory and critical care medicine":19.3,
"kidney international supplements":19.3,
"academy of management review":19.3,
"pharmacological reviews":19.3,
"acs energy letters":19.3,
"nature chemistry":19.2,
"chem":19.1,
"clinical microbiology reviews":19,
"reports on progress in physics":19,
"nature metabolism":18.9,
"energy storage materials":18.9,
"nature machine intelligence":18.8,
"science bulletin":18.8,
"susmat":18.7,
"progress in retinal and eye research":18.6,
"journal of advanced ceramics":18.6,
"advanced functional materials":18.5,
"psychological science in the public interest":18.2,
"bioactive materials":18,
"annual review of clinical psychology":17.8,
"nature physics":17.6,
"science immunology":17.6,
"periodontology 2000":17.5,
"psychological bulletin":17.3,
"computational visual media":17.3,
"nature cell biology":17.3,
"matter":17.3,
"trends in plant science":17.3,
"advanced fiber materials":17.2,
"ieee reviews in biomedical engineering":17.2,
"molecular plant":17.1,
"american journal of bioethics":17,
"nature aging":17,
"european journal of heart failure":16.9,
"nature reviews psychology":16.8,
"wiley interdisciplinary reviews-computational molecular science":16.8,
"nano energy":16.8,
"international materials reviews":16.8,
"military medical research":16.7,
"trends in cognitive sciences":16.7,
"trends in ecology & evolution":16.7,
"behavioral and brain sciences":16.6,
"european respiratory journal":16.6,
"nucleic acids research":16.6,
"circulation research":16.5,
"neuro-oncology":16.4,
"accounts of chemical research":16.4,
"acta numerica":16.3,
"psychotherapy and psychosomatics":16.3,
"national science review":16.3,
"renewable & sustainable energy reviews":16.3,
"ieee geoscience and remote sensing magazine":16.2,
"angewandte chemie-international edition":16.1,
"international journal of extreme manufacturing":16.1,
"advances in colloid and interface science":15.9,
"nature plants":15.8,
"science translational medicine":15.8,
"journal of magnesium and alloys":15.8,
"drug resistance updates":15.8,
"acs nano":15.8,
"jama surgery":15.7,
"nature geoscience":15.7,
"photonix":15.7,
"annual review of physiology":15.7,
"chinese journal of catalysis":15.7,
"advances in methods and practices in psychological science":15.6,
"journal of innovation & knowledge":15.6,
"journal of extracellular vesicles":15.5,
"annual review of environment and resources":15.5,
"lancet haematology":15.4,
"opto-electronic advances":15.3,
"ieee-caa journal of automatica sinica":15.3,
"smartmat":15.3,
"advanced drug delivery reviews":15.2,
"american journal of psychiatry":15.1,
"trends in food science & technology":15.1,
"annual review of medicine":15.1,
"one earth":15.1,
"lancet rheumatology":15,
"annual review of entomology":15,
"etransportation":15,
"environmental chemistry letters":15,
"molecular neurodegeneration":14.9,
"jama cardiology":14.8,
"kidney international":14.8,
"diabetes care":14.8,
"human reproduction update":14.8,
"journal of the national comprehensive cancer network":14.8,
"energy material advances":14.8,
"neuron":14.7,
"acta pharmaceutica sinica b":14.7,
"information fusion":14.7,
"nature communications":14.7,
"trends in neurosciences":14.6,
"autophagy":14.6,
"molecular cell":14.5,
"progress in particle and nuclear physics":14.5,
"journal of the american chemical society":14.4,
"biofuel research journal-brj":14.4,
"annual review of organizational psychology and organizational behavior":14.3,
"academy of management annals":14.3,
"journal of infection":14.3,
"bone research":14.3,
"educational psychologist":14.3,
"annual review of marine science":14.3,
"trends in cancer":14.3,
"advanced science":14.3,
"trends in biotechnology":14.3,
"annual review of condensed matter physics":14.3,
"studies in mycology":14.1,
"international journal of machine tools & manufacture":14,
"accounts of materials research":14,
"ieee transactions on intelligent vehicles":14,
"clinical and molecular hepatology":14,
"environmental science and ecotechnology":14,
"journal of energy chemistry":14,
"progress in lipid research":14,
"trends in microbiology":14,
"trends in chemistry":14,
"nature ecology & evolution":13.9,
"trends in pharmacological sciences":13.9,
"small structures":13.9,
"aggregate":13.9,
"ieee journal on selected areas in communications":13.8,
"microbiome":13.8,
"clinical psychology review":13.7,
"cell death and differentiation":13.7,
"physics of life reviews":13.7,
"lancet regional health-europe":13.6,
"energy economics":13.6,
"trends in genetics":13.6,
"protein & cell":13.6,
"lancet healthy longevity":13.4,
"nano convergence":13.4,
"journal of clinical investigation":13.3,
"chemical engineering journal":13.3,
"computer science review":13.3,
"nano today":13.2,
"ophthalmology":13.1,
"nature protocols":13.1,
"biochar":13.1,
"trends in immunology":13.1,
"alzheimers & dementia":13,
"drugs":13,
"journal of ocean engineering and science":13,
"cell discovery":13,
"small":13,
"energy & environmental materials":13,
"advances in applied energy":13,
"trends in cell biology":13,
"hepatology":12.9,
"nature astronomy":12.9,
"nature chemical biology":12.9,
"technological forecasting and social change":12.9,
"blood cancer journal":12.9,
"med":12.8,
"journal of the american academy of dermatology":12.8,
"jacc-cardiovascular imaging":12.8,
"biomaterials":12.8,
"lancet hiv":12.8,
"leukemia":12.8,
"trends in molecular medicine":12.8,
"annual review of biomedical engineering":12.8,
"journal of photochemistry and photobiology c-photochemistry reviews":12.8,
"composites part b-engineering":12.7,
"acs central science":12.7,
"journal of experimental medicine":12.6,
"allergy":12.6,
"nano materials science":12.6,
"annual review of nutrition":12.6,
"international journal of surgery":12.5,
"analytic methods in accident research":12.5,
"nature structural & molecular biology":12.5,
"communications in transportation research":12.5,
"business strategy and the environment":12.5,
"cancer research":12.5,
"ageing research reviews":12.5,
"npj digital medicine":12.4,
"theranostics":12.4,
"resources environment and sustainability":12.4,
"american psychologist":12.3,
"applied computing and informatics":12.3,
"npj flexible electronics":12.3,
"gut microbes":12.2,
"journal of manufacturing systems":12.2,
"journal of hazardous materials":12.2,
"materials horizons":12.2,
"applied mechanics reviews":12.2,
"current opinion in solid state & materials science":12.2,
"radiology":12.1,
"seminars in cancer biology":12.1,
"nature reviews urology":12.1,
"molecular therapy":12.1,
"annual review of neuroscience":12.1,
"annual review of biochemistry":12.1,
"biotechnology advances":12.1,
"nature computational science":12,
"jacc: cardiooncology":12,
"pharmacology & therapeutics":12,
"materials futures":12,
"comprehensive reviews in food science and food safety":12,
"journal of hospitality marketing & management":11.9,
"applied physics reviews":11.9,
"gigascience":11.8,
"trac-trends in analytical chemistry":11.8,
"energy materials":11.8,
"international journal of mining science and technology":11.7,
"qualitative psychology":11.7,
"jacc-cardiovascular interventions":11.7,
"ieee transactions on evolutionary computation":11.7,
"science advances":11.7,
"ieee transactions on industrial informatics":11.7,
"cell reports medicine":11.7,
"new astronomy reviews":11.7,
"annual review of physical chemistry":11.7,
"british journal of sports medicine":11.6,
"physical review x":11.6,
"clinical gastroenterology and hepatology":11.6,
"international journal of computer vision":11.6,
"liver cancer":11.6,
"trends in biochemical sciences":11.6,
"jama dermatology":11.5,
"journal of economic literature":11.5,
"endoscopy":11.5,
"industrial and organizational psychology-perspectives on science and practice":11.5,
"genomics proteomics & bioinformatics":11.5,
"blood cancer discovery":11.5,
"journal of marketing":11.5,
"chem catalysis":11.5,
"progress in aerospace sciences":11.5,
"progress in energy":11.5,
"arthritis & rheumatology":11.4,
"journal of allergy and clinical immunology":11.4,
"journal of advanced research":11.4,
"journal of experimental & clinical cancer research":11.4,
"water research":11.4,
"trends in endocrinology and metabolism":11.4,
"annual review of cell and developmental biology":11.4,
"critical reviews in environmental science and technology":11.4,
"endocrine pathology":11.3,
"acs catalysis":11.3,
"annual review of earth and planetary sciences":11.3,
"earth system science data":11.2,
"journal of materials science & technology":11.2,
"annual review of control robotics and autonomous systems":11.2,
"annual review of pharmacology and toxicology":11.2,
"journal of business logistics":11.2,
"sleep medicine reviews":11.2,
"resources conservation and recycling":11.2,
"annual review of ecology evolution and systematics":11.2,
"communications of the acm":11.1,
"quarterly journal of economics":11.1,
"technovation":11.1,
"cell genomics":11.1,
"remote sensing of environment":11.1,
"trends in environmental analytical chemistry":11.1,
"small science":11.1,
"polymer reviews":11.1,
"statistics surveys":11,
"british journal of dermatology":11,
"biological reviews":11,
"molecular biology and evolution":11,
"journal of retailing and consumer services":11,
"food hydrocolloids":11,
"tourism management":10.9,
"ieee wireless communications":10.9,
"clinical microbiology and infection":10.9,
"sustainable production and consumption":10.9,
"cement and concrete research":10.9,
"medicinal research reviews":10.9,
"international journal of oral science":10.8,
"siam review":10.8,
"isme journal":10.8,
"global change biology":10.8,
"translational neurodegeneration":10.8,
"metabolism-clinical and experimental":10.8,
"ieee transactions on image processing":10.8,
"earth-science reviews":10.8,
"cement & concrete composites":10.8,
"environmental science & technology":10.8,
"acta physico-chimica sinica":10.8,
"ieee transactions on fuzzy systems":10.7,
"medical image analysis":10.7,
"developmental cell":10.7,
"biosensors & bioelectronics":10.7,
"carbohydrate polymers":10.7,
"asian journal of pharmaceutical sciences":10.7,
"redox biology":10.7,
"medcomm":10.7,
"green energy & environment":10.7,
"artificial intelligence review":10.7,
"journal of materials chemistry a":10.7,
"ecomat":10.7,
"small methods":10.7,
"brain":10.6,
"isprs journal of photogrammetry and remote sensing":10.6,
"journal of nanobiotechnology":10.6,
"molecular horticulture":10.6,
"annual review of food science and technology":10.6,
"annual review of materials research":10.6,
"american economic review":10.5,
"perspectives on psychological science":10.5,
"jama network open":10.5,
"international journal of transgender health":10.5,
"plos medicine":10.5,
"journal of business research":10.5,
"journal of controlled release":10.5,
"sustainable cities and society":10.5,
"cyborg and bionic systems":10.5,
"carbon":10.5,
"annals of tourism research":10.4,
"genome medicine":10.4,
"journal of financial economics":10.4,
"journal of industrial information integration":10.4,
"pulmonology":10.4,
"annual review of biophysics":10.4,
"science china-chemistry":10.4,
"npj clean water":10.4,
"carbon capture science & technology":10.4,
"journal of the american society of nephrology":10.3,
"jacc-heart failure":10.3,
"journal for immunotherapy of cancer":10.3,
"additive manufacturing":10.3,
"environment international":10.3,
"ieee computational intelligence magazine":10.3,
"cardiovascular research":10.2,
"ieee transactions on neural networks and learning systems":10.2,
"journal of supply chain management":10.2,
"virtual and physical prototyping":10.2,
"natural product reports":10.2,
"journal of high energy astrophysics":10.2,
"technology in society":10.1,
"engineering":10.1,
"genome biology":10.1,
"educational psychology review":10.1,
"environmental health perspectives":10.1,
"facta universitatis-series mechanical engineering":10.1,
"european review of social psychology":10.1,
"plant biotechnology journal":10.1,
"american journal of hematology":10.1,
"journal of product innovation management":10.1,
"applied energy":10.1,
"fems microbiology reviews":10.1,
"mycosphere":10,
"clinical cancer research":10,
"plant cell":10,
"materials today physics":10,
"frontiers in ecology and the environment":10,
"advanced healthcare materials":10,
"eurosurveillance":9.9,
"international journal of hospitality management":9.9,
"sustainable development":9.9,
"journal of econometrics":9.9,
"jnci-journal of the national cancer institute":9.9,
"energy conversion and management":9.9,
"advanced industrial and engineering polymer research":9.9,
"family business review":9.9,
"soil biology & biochemistry":9.8,
"environmental impact assessment review":9.8,
"international journal of production economics":9.8,
"journal of service research":9.8,
"laser & photonics reviews":9.8,
"global food security-agriculture policy economics and environment":9.8,
"annual review of political science":9.7,
"journal of physiotherapy":9.7,
"journal of sport and health science":9.7,
"ebiomedicine":9.7,
"radiologia medica":9.7,
"bioresource technology":9.7,
"journal of cleaner production":9.7,
"biochimica et biophysica acta-reviews on cancer":9.7,
"archives of computational methods in engineering":9.7,
"view":9.7,
"educational research review":9.6,
"eclinicalmedicine":9.6,
"molecular psychiatry":9.6,
"biological psychiatry":9.6,
"ieee transactions on affective computing":9.6,
"american journal of public health":9.6,
"journal of research in interactive marketing":9.6,
"automation in construction":9.6,
"nano letters":9.6,
"acs materials letters":9.6,
"cancer treatment reviews":9.6,
"rare metals":9.6,
"energy and ai":9.6,
"clinical nuclear medicine":9.6,
"autism in adulthood":9.5,
"persoonia":9.5,
"academy of management journal":9.5,
"chest":9.5,
"journal of the academy of marketing science":9.5,
"jhep reports":9.5,
"journal of family business strategy":9.5,
"current obesity reports":9.5,
"jama health forum":9.5,
"experimental and molecular medicine":9.5,
"biomarker research":9.5,
"nano research":9.5,
"transport reviews":9.5,
"american journal of kidney diseases":9.4,
"ieee signal processing magazine":9.4,
"nature cardiovascular research":9.4,
"journal of applied psychology":9.4,
"monographs of the society for research in child development":9.4,
"proceedings of the national academy of sciences of the united states of america":9.4,
"journal of international financial management & accounting":9.4,
"canadian medical association journal":9.4,
"international journal of plasticity":9.4,
"journal of rock mechanics and geotechnical engineering":9.4,
"ieee transactions on cybernetics":9.4,
"journal of cachexia sarcopenia and muscle":9.4,
"ccs chemistry":9.4,
"ieee transactions on robotics":9.4,
"plant communications":9.4,
"embo journal":9.4,
"reliability engineering & system safety":9.4,
"acta biomaterialia":9.4,
"chinese chemical letters":9.4,
"experimental hematology & oncology":9.4,
"journal of colloid and interface science":9.4,
"npj computational materials":9.4,
"wiley interdisciplinary reviews-climate change":9.4,
"acta neuropathologica":9.3,
"prx quantum":9.3,
"sports medicine":9.3,
"journal of management":9.3,
"energy policy":9.3,
"journal of integrative plant biology":9.3,
"journal of neuroinflammation":9.3,
"current climate change reports":9.3,
"green chemistry":9.3,
"cytokine & growth factor reviews":9.3,
"current opinion in green and sustainable chemistry":9.3,
"journal of educational evaluation for health professions":9.3,
"catalysis reviews-science and engineering":9.3,
"journal of the american academy of child and adolescent psychiatry":9.2,
"angiogenesis":9.2,
"cellular & molecular biology letters":9.2,
"autoimmunity reviews":9.2,
"anesthesiology":9.1,
"journal of nuclear medicine":9.1,
"british journal of anaesthesia":9.1,
"international journal of contemporary hospitality management":9.1,
"leadership quarterly":9.1,
"pharmacological research":9.1,
"robotics and computer-integrated manufacturing":9.1,
"npj urban sustainability":9.1,
"cancer letters":9.1,
"circulation-arrhythmia and electrophysiology":9.1,
"journal of travel medicine":9.1,
"npj 2d materials and applications":9.1,
"annual review of nuclear and particle science":9.1
}

var fieldName = "series";
var newValue = "";

var fieldID = Zotero.ItemFields.getID(fieldName);
var s = new Zotero.Search();
s.libraryID = ZoteroPane.getSelectedLibraryID();
var ids = await s.search();
if (!ids.length) {
return "No items found";
}
await Zotero.DB.executeTransaction(async function () {
for (let id of ids) {
let item = await Zotero.Items.getAsync(id);
let mappedFieldID = Zotero.ItemFields.getFieldIDFromTypeAndBase(item.itemTypeID, fieldName);
var IF=impact_factors[item.getField('publicationTitle').toLowerCase()]
item.setField(mappedFieldID ? mappedFieldID : fieldID, newValue);
if(IF!=undefined){
    item.setField('series',IF)
}

await item.save();
}
});
return ids.length + " item(s) IF updated, and shown in series field!";
