var impact_factors={
"seminars in cancer biology": 12.1,      /* :contentReference[oaicite:0]{index=0} */
"biocybernetics and biomedical engineering": 6.9,      /* :contentReference[oaicite:1]{index=1} */
"biomedical signal processing and control": 6.8,      /* :contentReference[oaicite:2]{index=2} */
"computer methods and programs in biomedicine": 4.9,   /* :contentReference[oaicite:3]{index=3} */
"alexandria engineering journal": 6.2,   /* :contentReference[oaicite:4]{index=4} */
"computers in biology and medicine": 8.4, /* :contentReference[oaicite:5]{index=5} */
"image and vision computing": 4.2,       /* :contentReference[oaicite:6]{index=6} */
"computers and electrical engineering": 5.7,  /* :contentReference[oaicite:7]{index=7} */
"methodsx": 1.6,                         /* :contentReference[oaicite:8]{index=8} */
"machine learning with applications":7.5,
"knowledge-based systems": 7.2,          /* :contentReference[oaicite:9]{index=9} */
"academic radiology": 3.8,                /* :contentReference[oaicite:10]{index=10} */
"journal of cosmetic science":0.2,
"bunseki kagaku":0.2,
"international journal of nanotechnology":0.3,
"kagaku kogaku ronbunshu":0.3,
"journal of chemical crystallography":0.4,
"journal of photopolymer science and technology":0.4,
"polymer-korea":0.4,
"revue roumaine de chimie":0.4,
"acta crystallographica section e-crystallographic communications":0.5,
"quimica nova":0.5,
"journal of water chemistry and technology":0.5,
"tappi journal":0.6,
"materiale plastice":0.6,
"russian journal of applied chemistry":0.6,
"journal of chemical engineering of japan":0.6,
"acta crystallographica section c-structural chemistry":0.7,
"fibres & textiles in eastern europe":0.7,
"indian journal of engineering and materials sciences":0.7,
"international journal of materials research":0.7,
"letters in organic chemistry":0.7,
"sains malaysiana":0.7,
"molecular crystals and liquid crystals":0.7,
"materials science":0.7,
"polish journal of chemical technology":0.7,
"chemical journal of chinese universities-chinese":0.7,
"russian journal of physical chemistry a":0.7,
"zeitschrift fur naturforschung section b-a journal of chemical sciences":0.8,
"acta physica sinica":0.8,
"optics and spectroscopy":0.8,
"materials science-medziagotyra":0.8,
"hemijska industrija":0.8,
"chinese journal of inorganic chemistry":0.8,
"doklady chemistry":0.8,
"journal of porphyrins and phthalocyanines":0.9,
"bulletin of experimental biology and medicine":0.9,
"condensed matter physics":0.9,
"physics of the solid state":0.9,
"nordic pulp & paper research journal":0.9,
"journal of labelled compounds & radiopharmaceuticals":0.9,
"international journal of clothing science and technology":1,
"journal of the faculty of engineering and architecture of gazi university":1,
"journal of liquid chromatography & related technologies":1,
"proceedings of the institution of mechanical engineers part g-journal of aerospace engineering":1,
"journal of analytical chemistry":1,
"polimeros-ciencia e tecnologia":1,
"bio-medical materials and engineering":1,
"polymer science series b":1,
"desalination and water treatment":1,
"journal of chemical research":1,
"polymer science series a":1,
"journal of the serbian chemical society":1,
"nano":1,
"australian journal of chemistry":1,
"turkish journal of biology":1.1,
"zeitschrift fur anorganische und allgemeine chemie":1.1,
"corrosion":1.1,
"protection of metals and physical chemistry of surfaces":1.1,
"doklady physical chemistry":1.1,
"autex research journal":1.1,
"progress in rubber plastics and recycling technology":1.1,
"polimery":1.1,
"russian journal of bioorganic chemistry":1.1,
"international polymer processing":1.1,
"canadian journal of chemistry":1.1,
"chimia":1.1,
"russian journal of electrochemistry":1.1,
"chromatographia":1.2,
"laser physics":1.2,
"rubber chemistry and technology":1.2,
"comptes rendus chimie":1.2,
"materials transactions":1.2,
"maderas-ciencia y tecnologia":1.2,
"chinese journal of analytical chemistry":1.2,
"journal of carbohydrate chemistry":1.2,
"journal of macromolecular science part b-physics":1.2,
"jove-journal of visualized experiments":1.2,
"journal of structural chemistry":1.2,
"acta chimica slovenica":1.2,
"functional materials letters":1.2,
"international journal of chemical reactor engineering":1.2,
"acta crystallographica section b-structural science crystal engineering and materials":1.3,
"ieee transactions on plasma science":1.3,
"opto-electronics review":1.3,
"journal of wuhan university of technology-materials science edition":1.3,
"nihon reoroji gakkaishi":1.3,
"bioresources":1.3,
"cellulose chemistry and technology":1.3,
"bioinspired biomimetic and nanobiomaterials":1.3,
"journal of the brazilian chemical society":1.3,
"pigment & resin technology":1.3,
"international journal of electrochemical science":1.3,
"turkish journal of chemistry":1.3,
"journal of strain analysis for engineering design":1.4,
"phosphorus sulfur and silicon and the related elements":1.4,
"biocatalysis and biotransformation":1.4,
"inorganic and nano-metal chemistry":1.4,
"journal of solution chemistry":1.4,
"bioscience biotechnology and biochemistry":1.4,
"journal of elastomers and plastics":1.4,
"aip advances":1.4,
"asia-pacific journal of chemical engineering":1.4,
"chemistry letters":1.4,
"colloid journal":1.4,
"current nanoscience":1.4,
"journal of asian architecture and building engineering":1.5,
"journal of microscopy":1.5,
"journal of wound care":1.5,
"phytoparasitica":1.5,
"brazilian journal of physics":1.5,
"journal of mechanical science and technology":1.5,
"journal of the physical society of japan":1.5,
"science and engineering of composite materials":1.5,
"micro & nano letters":1.5,
"journal of radioanalytical and nuclear chemistry":1.5,
"tetrahedron letters":1.5,
"chemical & pharmaceutical bulletin":1.5,
"clean-soil air water":1.5,
"corrosion engineering science and technology":1.5,
"mechanics of composite materials":1.5,
"pharmazie":1.5,
"helvetica chimica acta":1.5,
"materials research-ibero-american journal of materials":1.5,
"transition metal chemistry":1.6,
"analytical letters":1.6,
"journal of medical and biological engineering":1.6,
"molecular physics":1.6,
"transportation research record":1.6,
"materials and corrosion-werkstoffe und korrosion":1.6,
"microelectronics reliability":1.6,
"journal of the chilean chemical society":1.6,
"applied radiation and isotopes":1.6,
"textile research journal":1.6,
"biointerphases":1.6,
"journal of the chinese chemical society":1.6,
"canadian journal of chemical engineering":1.6,
"soft materials":1.6,
"chemical and biochemical engineering quarterly":1.6,
"surface and interface analysis":1.6,
"journal of surfactants and detergents":1.6,
"complexity":1.7,
"journal of spectroscopy":1.7,
"computer methods in biomechanics and biomedical engineering":1.7,
"current organic synthesis":1.7,
"materials science and technology":1.7,
"current organic chemistry":1.7,
"journal of wood chemistry and technology":1.7,
"journal of fluorine chemistry":1.7,
"journal of biomechanical engineering-transactions of the asme":1.7,
"acta polymerica sinica":1.7,
"international journal of polymer analysis and characterization":1.7,
"journal of polymer engineering":1.7,
"journal of inorganic materials":1.7,
"proceedings of the institution of mechanical engineers part h-journal of engineering in medicine":1.7,
"journal of chemical sciences":1.7,
"advances in natural sciences-nanoscience and nanotechnology":1.7,
"monatshefte fur chemie":1.7,
"russian chemical bulletin":1.7,
"acta chimica sinica":1.7,
"journal of inclusion phenomena and macrocyclic chemistry":1.7,
"environmental entomology":1.8,
"journal of the optical society of america b-optical physics":1.8,
"epl":1.8,
"proceedings of the institution of mechanical engineers part c-journal of mechanical engineering science":1.8,
"advanced composite materials":1.8,
"green materials":1.8,
"mrs communications":1.8,
"rapid communications in mass spectrometry":1.8,
"russian journal of inorganic chemistry":1.8,
"journal of the australian ceramic society":1.8,
"designed monomers and polymers":1.8,
"materials research express":1.8,
"high performance polymers":1.8,
"analytical sciences":1.8,
"chinese journal of organic chemistry":1.8,
"ecs journal of solid state science and technology":1.8,
"solvent extraction and ion exchange":1.8,
"macromolecular theory and simulations":1.8,
"european physical journal e":1.8,
"mendeleev communications":1.8,
"macromolecular reaction engineering":1.8,
"chemical engineering & technology":1.8,
"meccanica":1.9,
"chemical engineering communications":1.9,
"journal of chemometrics":1.9,
"molecular simulation":1.9,
"chemistryselect":1.9,
"bulletin of materials science":1.9,
"journal of environmental science and health part a-toxic/hazardous substances & environmental engineering":1.9,
"journal of dispersion science and technology":1.9,
"bioremediation journal":1.9,
"applied physics b-lasers and optics":2,
"biotechnology letters":2,
"experimental mechanics":2,
"clays and clay minerals":2,
"acta mechanica solida sinica":2,
"recent patents on nanotechnology":2,
"chemical physics":2,
"journal of chemical and engineering data":2,
"thin solid films":2,
"advances in polymer technology":2,
"coloration technology":2,
"pure and applied chemistry":2,
"jom":2.1,
"clinical hemorheology and microcirculation":2.1,
"structural chemistry":2.1,
"ieee transactions on magnetics":2.1,
"journal of molecular modeling":2.1,
"advances in structural engineering":2.1,
"supramolecular chemistry":2.1,
"journal of organometallic chemistry":2.1,
"tetrahedron":2.1,
"journal of macromolecular science part a-pure and applied chemistry":2.1,
"polymers & polymer composites":2.1,
"journal of bioactive and compatible polymers":2.1,
"composite interfaces":2.1,
"chemical papers":2.1,
"environmental progress & sustainable energy":2.1,
"plastics rubber and composites":2.1,
"gold bulletin":2.1,
"journal of nanoparticle research":2.1,
"surface science":2.1,
"journal of economic entomology":2.2,
"laryngoscope":2.2,
"physical review e":2.2,
"symmetry-basel":2.2,
"bioimpacts":2.2,
"actuators":2.2,
"archive of applied mechanics":2.2,
"european biophysics journal with biophysics letters":2.2,
"journal of materials engineering and performance":2.2,
"journal of wood science":2.2,
"holzforschung":2.2,
"fibers and polymers":2.2,
"journal of coordination chemistry":2.2,
"european journal of inorganic chemistry":2.2,
"beilstein journal of organic chemistry":2.2,
"synthesis-stuttgart":2.2,
"journal of electronic materials":2.2,
"colloid and polymer science":2.2,
"korea-australia rheology journal":2.2,
"rheologica acta":2.3,
"applied physics express":2.3,
"international journal of environmental analytical chemistry":2.3,
"cellular and molecular bioengineering":2.3,
"anti-corrosion methods and materials":2.3,
"journal of physics-condensed matter":2.3,
"applied composite materials":2.3,
"israel journal of chemistry":2.3,
"international journal of quantum chemistry":2.3,
"journal of sol-gel science and technology":2.3,
"chemphyschem":2.3,
"journal of biomaterials applications":2.3,
"polymer journal":2.3,
"chemistry & biodiversity":2.3,
"3d printing and additive manufacturing":2.3,
"separation science and technology":2.3,
"journal of coatings technology and research":2.3,
"journal of reinforced plastics and composites":2.3,
"journal of composite materials":2.3,
"catalysis letters":2.3,
"bulletin of the korean chemical society":2.3,
"particulate science and technology":2.3,
"journal of manufacturing science and engineering-transactions of the asme":2.4,
"journal of vacuum science & technology a":2.4,
"european journal of wood and wood products":2.4,
"crystals":2.4,
"polycyclic aromatic compounds":2.4,
"liquid crystals":2.4,
"carbohydrate research":2.4,
"iranian polymer journal":2.4,
"current applied physics":2.4,
"surface engineering":2.4,
"ionics":2.4,
"journal of intelligent material systems and structures":2.4,
"journal of chemical education":2.5,
"journal of microelectromechanical systems":2.5,
"organometallics":2.5,
"bioorganic & medicinal chemistry letters":2.5,
"european journal of organic chemistry":2.5,
"applied sciences-basel":2.5,
"applied physics a-materials science & processing":2.5,
"macromolecular chemistry and physics":2.5,
"water environment research":2.5,
"international journal of polymeric materials and polymeric biomaterials":2.5,
"water science and technology":2.5,
"journal of porous materials":2.5,
"chemistryopen":2.5,
"frontiers of materials science":2.5,
"nano futures":2.5,
"heritage science":2.6,
"international wound journal":2.6,
"physica scripta":2.6,
"optical fiber technology":2.6,
"journal of applied mechanics-transactions of the asme":2.6,
"chembiochem":2.6,
"biomicrofluidics":2.6,
"ieee electrical insulation magazine":2.6,
"journal of food science and technology-mysore":2.6,
"arabian journal for science and engineering":2.6,
"international journal of modern physics b":2.6,
"microelectronic engineering":2.6,
"journal of energy resources technology-transactions of the asme":2.6,
"crystengcomm":2.6,
"analytical biochemistry":2.6,
"journal of fluorescence":2.6,
"journal of polymer research":2.6,
"journal of experimental nanoscience":2.6,
"polymer-plastics technology and materials":2.6,
"chemnanomat":2.6,
"frontiers in materials":2.6,
"journal of solid state electrochemistry":2.6,
"fuel cells":2.6,
"beilstein journal of nanotechnology":2.6,
"journal of biomolecular structure & dynamics":2.7,
"analytical methods":2.7,
"journal of bacteriology":2.7,
"surface innovations":2.7,
"journal of applied physics":2.7,
"journal of non-newtonian fluid mechanics":2.7,
"photochemical & photobiological sciences":2.7,
"journal of material cycles and waste management":2.7,
"inorganica chimica acta":2.7,
"journal of cluster science":2.7,
"vibrational spectroscopy":2.7,
"express polymer letters":2.7,
"journal of physical chemistry a":2.7,
"materials letters":2.7,
"organic electronics":2.7,
"drying technology":2.7,
"journal of applied polymer science":2.7,
"new journal of chemistry":2.7,
"electroanalysis":2.7,
"journal of adhesion science and technology":2.7,
"journal of materials research":2.7,
"particle & particle systems characterization":2.7,
"physica a-statistical mechanics and its applications":2.8,
"geosynthetics international":2.8,
"new journal of physics":2.8,
"advances in space research":2.8,
"journal of pharmacy and pharmacology":2.8,
"optical materials express":2.8,
"environmental earth sciences":2.8,
"journal of separation science":2.8,
"flexible and printed electronics":2.8,
"journal of natural fibers":2.8,
"radiation physics and chemistry":2.8,
"journal of chromatography b-analytical technologies in the biomedical and life sciences":2.8,
"asian journal of organic chemistry":2.8,
"chemical physics letters":2.8,
"chirality":2.8,
"journal of materials science-materials in electronics":2.8,
"research on chemical intermediates":2.8,
"macromolecular research":2.8,
"silicon":2.8,
"journal of physical chemistry b":2.8,
"fluid phase equilibria":2.8,
"journal of chemical technology and biotechnology":2.8,
"processes":2.8,
"adsorption science & technology":2.8,
"journal of chemistry":2.8,
"iucrj":2.9,
"journal of composites for construction":2.9,
"proceedings of the royal society a-mathematical physical and engineering sciences":2.9,
"international journal of applied mechanics":2.9,
"plasma processes and polymers":2.9,
"tribology letters":2.9,
"international journal of advanced manufacturing technology":2.9,
"royal society open science":2.9,
"plos one":2.9,
"organic & biomolecular chemistry":2.9,
"physical chemistry chemical physics":2.9,
"ieee transactions on dielectrics and electrical insulation":2.9,
"soft matter":2.9,
"nanotechnology":2.9,
"coatings":2.9,
"polymer international":2.9,
"materials technology":2.9,
"journal of adhesion":2.9,
"korean journal of chemical engineering":2.9,
"journal of rheology":3,
"journal of computer-aided molecular design":3,
"water":3,
"journal of structural biology":3,
"international journal of environmental science and technology":3,
"journal of thermal analysis and calorimetry":3,
"journal of microencapsulation":3,
"electrophoresis":3,
"micromachines":3,
"solid state ionics":3,
"computational and theoretical chemistry":3,
"zeitschrift fur physikalische chemie-international journal of research in physical chemistry & chemical physics":3,
"chemphotochem":3,
"chempluschem":3,
"acta astronautica":3.1,
"optics letters":3.1,
"inorganics":3.1,
"journal of materials in civil engineering":3.1,
"journal of physics d-applied physics":3.1,
"physical review materials":3.1,
"annales de dermatologie et de venereologie":3.1,
"wood science and technology":3.1,
"journal of chemical physics":3.1,
"journal of the american society for mass spectrometry":3.1,
"bioinspiration & biomimetics":3.1,
"journal of the electrochemical society":3.1,
"thermochimica acta":3.1,
"computational materials science":3.1,
"polymers for advanced technologies":3.1,
"journal of tissue engineering and regenerative medicine":3.1,
"polymer bulletin":3.1,
"materials":3.1,
"nanomaterials and nanotechnology":3.1,
"chemical research in chinese universities":3.1,
"optics express":3.2,
"biophysical journal":3.2,
"environmental geochemistry and health":3.2,
"journal of non-crystalline solids":3.2,
"e-polymers":3.2,
"biopolymers":3.2,
"crystal growth & design":3.2,
"journal of solid state chemistry":3.2,
"luminescence":3.2,
"international journal of adhesion and adhesives":3.2,
"polymer engineering and science":3.2,
"journal of biomedical materials research part b-applied biomaterials":3.2,
"molecular systems design & engineering":3.2,
"journal of cellular plastics":3.2,
"journal of organic chemistry":3.3,
"bioorganic & medicinal chemistry":3.3,
"journal of the mechanical behavior of biomedical materials":3.3,
"sustainability":3.3,
"membranes":3.3,
"journal of physical chemistry c":3.3,
"faraday discussions":3.3,
"bulletin of the chemical society of japan":3.3,
"ieee access":3.4,
"international journal of solids and structures":3.4,
"mechanics of materials":3.4,
"biomimetics":3.4,
"materials and structures":3.4,
"glycobiology":3.4,
"road materials and pavement design":3.4,
"journal of supercritical fluids":3.4,
"advanced engineering materials":3.4,
"sensors":3.4,
"heliyon":3.4,
"solid state sciences":3.4,
"reaction chemistry & engineering":3.4,
"international journal of polymer science":3.4,
"optics and lasers in engineering":3.5,
"journal of sandwich structures & materials":3.5,
"journal of the american ceramic society":3.5,
"applied physics letters":3.5,
"geothermics":3.5,
"dalton transactions":3.5,
"pharmaceutical research":3.5,
"environmental science-water research & technology":3.5,
"journal of materials science":3.5,
"aiche journal":3.5,
"biomass conversion and biorefinery":3.5,
"chemelectrochem":3.5,
"chemistry-an asian journal":3.5,
"energy technology":3.6,
"analyst":3.6,
"journal of biomaterials science-polymer edition":3.6,
"journal of thermoplastic composite materials":3.6,
"reviews on advanced materials science":3.6,
"computational mechanics":3.7,
"advanced therapeutics":3.7,
"journal of the royal society interface":3.7,
"smart materials and structures":3.7,
"bulletin of engineering geology and the environment":3.7,
"chinese journal of chemical engineering":3.7,
"applied organometallic chemistry":3.7,
"journal of pharmaceutical sciences":3.7,
"process biochemistry":3.7,
"biochemical engineering journal":3.7,
"materials today communications":3.7,
"acs omega":3.7,
"langmuir":3.7,
"chemical engineering research & design":3.7,
"plos computational biology":3.8,
"acta mechanica sinica":3.8,
"bioengineering-basel":3.8,
"scientific reports":3.8,
"optical materials":3.8,
"journal of chromatography a":3.8,
"analytical and bioanalytical chemistry":3.8,
"journal of vinyl & additive technology":3.8,
"vacuum":3.8,
"industrial & engineering chemistry research":3.8,
"frontiers in chemistry":3.8,
"chemcatchem":3.8,
"catalysts":3.8,
"structures":3.9,
"journal of cereal science":3.9,
"frontiers in molecular biosciences":3.9,
"journal of inorganic and organometallic polymers and materials":3.9,
"journal of biomedical materials research part a":3.9,
"biomedical materials":3.9,
"chemistry-a european journal":3.9,
"materials science and engineering b-advanced functional solid-state materials":3.9,
"rsc advances":3.9,
"molecular catalysis":3.9,
"journal of polymer science":3.9,
"international journal of damage mechanics":4,
"journal of biological chemistry":4,
"bioconjugate chemistry":4,
"synthetic metals":4,
"journal of molecular structure":4,
"ndt & e international":4.1,
"mrs bulletin":4.1,
"sensors and actuators a-physical":4.1,
"dyes and pigments":4.1,
"polymer":4.1,
"polymer chemistry":4.1,
"journal of electroanalytical chemistry":4.1,
"chinese journal of polymer science":4.1,
"materials and manufacturing processes":4.1,
"chemical engineering science":4.1,
"journal of photochemistry and photobiology a-chemistry":4.1,
"methods":4.2,
"nanomedicine-nanotechnology biology and medicine":4.2,
"macromolecular rapid communications":4.2,
"advanced powder technology":4.2,
"macromolecular materials and engineering":4.2,
"journal of materials science-materials in medicine":4.2,
"molecules":4.2,
"nanocomposites":4.2,
"journal of prosthetic dentistry":4.3,
"spectrochimica acta part a-molecular and biomolecular spectroscopy":4.3,
"ieee sensors journal":4.3,
"environmental microbiology":4.3,
"acs applied electronic materials":4.3,
"advances in nano research":4.3,
"frontiers of chemical science and engineering":4.3,
"inorganic chemistry":4.3,
"extreme mechanics letters":4.3,
"materials chemistry and physics":4.3,
"frontiers in bioengineering and biotechnology":4.3,
"chemical communications":4.3,
"journal of physics and chemistry of solids":4.3,
"advanced materials interfaces":4.3,
"bmc chemistry":4.3,
"arthritis research & therapy":4.4,
"results in physics":4.4,
"computational and structural biotechnology journal":4.4,
"catalysis science & technology":4.4,
"engineering failure analysis":4.4,
"inorganic chemistry communications":4.4,
"ieee transactions on biomedical engineering":4.4,
"science china-technological sciences":4.4,
"high voltage":4.4,
"acs applied polymer materials":4.4,
"tissue engineering and regenerative medicine":4.4,
"nanomaterials":4.4,
"macromolecular bioscience":4.4,
"proceedings of the japan academy series b-physical and biological sciences":4.4,
"journal of drug delivery science and technology":4.5,
"molecular pharmaceutics":4.5,
"vaccine":4.5,
"artificial cells nanomedicine and biotechnology":4.5,
"reactive & functional polymers":4.5,
"cancer nanotechnology":4.5,
"dental materials":4.6,
"scipost physics":4.6,
"organic chemistry frontiers":4.6,
"ieee robotics and automation letters":4.6,
"frontiers in cellular and infection microbiology":4.6,
"iscience":4.6,
"batteries-basel":4.6,
"nanoscale advances":4.6,
"neuroimage":4.7,
"journal of physiology-london":4.7,
"engineering fracture mechanics":4.7,
"foods":4.7,
"transactions of nonferrous metals society of china":4.7,
"journal of molecular biology":4.7,
"current opinion in biomedical engineering":4.7,
"geotextiles and geomembranes":4.7,
"polymers":4.7,
"applied catalysis a-general":4.7,
"environment development and sustainability":4.7,
"colloid and interface science communications":4.7,
"electrochemistry communications":4.7,
"journal of polymers and the environment":4.7,
"nanomedicine":4.7,
"journal of physical chemistry letters":4.8,
"progress in natural science-materials international":4.8,
"bioelectrochemistry":4.8,
"polymer composites":4.8,
"microporous and mesoporous materials":4.8,
"pharmaceutics":4.9,
"marine drugs":4.9,
"journal of natural gas science and engineering":4.9,
"organic letters":4.9,
"cellulose":4.9,
"microchemical journal":4.9,
"biosensors-basel":4.9,
"colloids and surfaces a-physicochemical and engineering aspects":4.9,
"international journal of molecular sciences":4.9,
"defence technology":5,
"international journal of heat and mass transfer":5,
"journal of the mechanics and physics of solids":5,
"polymer testing":5,
"gels":5,
"journal of functional biomaterials":5,
"sustainable energy & fuels":5,
"ceramics international":5.1,
"tissue engineering part b-reviews":5.1,
"acs macro letters":5.1,
"macromolecules":5.1,
"batteries & supercaps":5.1,
"life sciences":5.2,
"communications biology":5.2,
"catalysis today":5.2,
"energy & fuels":5.2,
"international journal of pharmaceutics":5.3,
"marine pollution bulletin":5.3,
"apl materials":5.3,
"advanced electronic materials":5.3,
"microchimica acta":5.3,
"journal of molecular liquids":5.3,
"applied clay science":5.3,
"surface & coatings technology":5.3,
"materials research bulletin":5.3,
"arabian journal of chemistry":5.3,
"acs applied nano materials":5.3,
"ieee robotics & automation magazine":5.4,
"colloids and surfaces b-biointerfaces":5.4,
"acs applied energy materials":5.4,
"acs biomaterials science & engineering":5.4,
"biomacromolecules":5.5,
"electrochimica acta":5.5,
"biomaterials advances":5.5,
"sustainable chemistry and pharmacy":5.5,
"chinese journal of chemistry":5.5,
"journal of the taiwan institute of chemical engineers":5.5,
"biochip journal":5.5,
"nanoscale research letters":5.5,
"carbon letters":5.5,
"industrial crops and products":5.6,
"engineering structures":5.6,
"talanta":5.6,
"regenerative biomaterials":5.6,
"international journal of engineering science":5.7,
"japanese dental science review":5.7,
"international journal of fatigue":5.7,
"drug delivery and translational research":5.7,
"journal of biological engineering":5.7,
"thin-walled structures":5.7,
"analytica chimica acta":5.7,
"journal of agricultural and food chemistry":5.7,
"surfaces and interfaces":5.7,
"journal of materials chemistry c":5.7,
"journal of analytical and applied pyrolysis":5.8,
"green chemistry letters and reviews":5.8,
"journal of the european ceramic society":5.8,
"journal of alloys and compounds":5.8,
"european polymer journal":5.8,
"environmental science-nano":5.8,
"nanoscale":5.8,
"biomaterials science":5.8,
"chinese journal of structural chemistry":5.9,
"communications chemistry":5.9,
"journal of industrial and engineering chemistry":5.9,
"ain shams engineering journal":6,
"solar rrl":6,
"materials chemistry frontiers":6,
"inorganic chemistry frontiers":6.1,
"journal of clinical microbiology":6.1,
"tribology international":6.1,
"bioengineering & translational medicine":6.1,
"journal of manufacturing processes":6.1,
"frontiers of environmental science & engineering":6.1,
"materials science and engineering a-structural materials properties microstructure and processing":6.1,
"journal of materials chemistry b":6.1,
"future generation computer systems-the international journal of escience":6.2,
"journal of materials research and technology-jmr&t":6.2,
"friction":6.3,
"polymer degradation and stability":6.3,
"composite structures":6.3,
"solar energy materials and solar cells":6.3,
"applied surface science":6.3,
"journal of water process engineering":6.3,
"soft robotics":6.4,
"advanced materials technologies":6.4,
"case studies in construction materials":6.5,
"nanophotonics":6.5,
"advanced sustainable systems":6.5,
"progress in organic coatings":6.5,
"composites communications":6.5,
"npj materials degradation":6.6,
"international journal of nanomedicine":6.6,
"journal of building engineering":6.7,
"computers & industrial engineering":6.7,
"journal of materials processing technology":6.7,
"fuel":6.7,
"analytical chemistry":6.7,
"environmental technology & innovation":6.7,
"materials today chemistry":6.7,
"journal of science-advanced materials and devices":6.7,
"advanced intelligent systems":6.8,
"science china-materials":6.8,
"petroleum exploration and development":7,
"chemical record":7,
"acs sustainable chemistry & engineering":7.1,
"materials today sustainability":7.1,
"waste management":7.1,
"journal of co2 utilization":7.2,
"applied materials today":7.2,
"chemistry of materials":7.2,
"corrosion science":7.4,
"construction and building materials":7.4,
"journal of environmental chemical engineering":7.4,
"science and technology of advanced materials":7.4,
"chemsuschem":7.5,
"environmental pollution":7.6,
"chemical science":7.6,
"materials & design":7.6,
"international journal of biological macromolecules":7.7,
"cell reports physical science":7.9,
"nanoscale horizons":8,
"sensors and actuators b-chemical":8,
"advanced optical materials":8,
"physical review letters":8.1,
"chemosphere":8.1,
"biomaterials research":8.1,
"composites part a-applied science and manufacturing":8.1,
"materials today advances":8.1,
"separation and purification technology":8.1,
"materials science & engineering c-materials for biological applications":8.1,
"journal of power sources":8.1,
"international journal of hydrogen energy":8.1,
"science of the total environment":8.2,
"biofabrication":8.2,
"acs sensors":8.2,
"acta materialia":8.3,
"desalination":8.3,
"composites science and technology":8.3,
"acs applied materials & interfaces":8.3,
"journal of membrane science":8.4,
"journal of materiomics":8.4,
"food chemistry":8.5,
"research":8.5,
"materials research letters":8.6,
"sustainable materials and technologies":8.6,
"npg asia materials":8.6,
"ultrasonics sonochemistry":8.7,
"materials today bio":8.7,
"journal of energy storage":8.9,
"environmental science & technology letters":8.9,
"energy":9,
"materials today energy":9,
"renewable energy":9,
"current opinion in green and sustainable chemistry":9.3,
"green chemistry":9.3,
"international journal of plasticity":9.4,
"ieee transactions on robotics":9.4,
"reliability engineering & system safety":9.4,
"proceedings of the national academy of sciences of the united states of america":9.4,
"acta biomaterialia":9.4,
"chinese chemical letters":9.4,
"journal of colloid and interface science":9.4,
"nano research":9.5,
"nano letters":9.6,
"acs materials letters":9.6,
"rare metals":9.6,
"journal of cleaner production":9.7,
"materials today physics":10,
"advanced healthcare materials":10,
"applied energy":10.1,
"engineering":10.1,
"additive manufacturing":10.3,
"science china-chemistry":10.4,
"journal of controlled release":10.5,
"carbon":10.5,
"journal of nanobiotechnology":10.6,
"ecomat":10.7,
"biosensors & bioelectronics":10.7,
"carbohydrate polymers":10.7,
"journal of materials chemistry a":10.7,
"small methods":10.7,
"earth-science reviews":10.8,
"cement & concrete composites":10.8,
"acta physico-chimica sinica":10.8,
"environmental science & technology":10.8,
"cement and concrete research":10.9,
"food hydrocolloids":11,
"journal of materials science & technology":11.2,
"resources conservation and recycling":11.2,
"acs catalysis":11.3,
"journal of advanced research":11.4,
"water research":11.4,
"physical review x":11.6,
"science advances":11.7,
"journal of hazardous materials":12.2,
"materials horizons":12.2,
"npj flexible electronics":12.3,
"composites part b-engineering":12.7,
"acs central science":12.7,
"biomaterials":12.8,
"small":13,
"energy & environmental materials":13,
"nature protocols":13.1,
"nano today":13.2,
"chemical engineering journal":13.3,
"nano convergence":13.4,
"journal of energy chemistry":14,
"advanced science":14.3,
"journal of the american chemical society":14.4,
"nature communications":14.7,
"environmental chemistry letters":15,
"chinese journal of catalysis":15.7,
"science translational medicine":15.8,
"acs nano":15.8,
"advances in colloid and interface science":15.9,
"angewandte chemie-international edition":16.1,
"national science review":16.3,
"nano energy":16.8,
"advanced fiber materials":17.2,
"matter":17.3,
"bioactive materials":18,
"advanced functional materials":18.5,
"susmat":18.7,
"science bulletin":18.8,
"energy storage materials":18.9,
"chem":19.1,
"nature chemistry":19.2,
"acs energy letters":19.3,
"applied catalysis b-environment and energy":20.2,
"coordination chemistry reviews":20.3,
"light-science & applications":20.6,
"materials today":21.1,
"infomat":22.7,
"proceedings of the ieee":23.2,
"advanced composites and hybrid materials":23.2,
"advanced energy materials":24.4,
"progress in polymer science":26,
"science robotics":26.1,
"nature biomedical engineering":26.8,
"advanced materials":27.4,
"nano-micro letters":31.6,
"energy & environmental science":32.4,
"nature materials":37.2,
"nature nanotechnology":38.1,
"joule":38.6,
"science":44.7,
"cell":45.5,
"nature":50.5,
"academic radiology": 3.08,
"acta informatica pragensia": 1.12,
"adcaij: advances in distributed computing and artificial intelligence journal": 1.7,
"advanced ultrasound in diagnosis and therapy": 0.19,
"applied sciences": 2.5,
"archives of computational methods in engineering": 11.41,
"array": 2.3,
"artificial intelligence review": 8.1,
"bmc bioinformatics": 2.9,
"biocybernetics and biomedical engineering": 5.3,
"biomedical engineering letters": 3.2,
"biomedical signal processing and control": 3.1,
"cancers": 4.5,
"clinical imaging": 1.81,
"computers in biology and medicine": 7.0,
"computer methods and programs in biomedicine": 4.9,
"critical reviews in oncology/hematology": 5.5,
"diagnostics": 3.0,
"electronics": 2.6,
"frontiers in oncology": 3.5,
"frontiers of medicine": 3.9,
"ieee access": 3.4,
"ieee journal of biomedical and health informatics": 7.6,
"ieee signal processing letters": 3.89,
"ieee transactions on pattern analysis and machine intelligence": 21.9,
"intelligent systems with applications": 5.81,
"international journal of biomedical imaging": 3.3,
"international journal of computational intelligence systems": 2.5,
"international journal of imaging systems and technology": 3.0,
"journal of ambient intelligence and humanized computing": 7.1,
"journal of healthcare engineering": 3.1,
"journal of imaging": 2.7,
"journal of medical imaging": 2.3,
"journal of sensors": 3.4,
"medical image analysis": 12.77,
"medical physics": 3.48,
"multimedia tools and applications": 4.5,
"neural networks": 6.0,
"npj breast cancer": 6.5,
"physica medica": 3.4,
"physics in medicine and biology": 3.3,
"plos one": 3.2,
"progress in biomedical engineering": 5.0,
"scientific data": 6.4,
"scientific reports": 4.3,
"tomography": 2.2,
"neurocomputing":5.5,
"procedia computer science":2.3
    
}

var fieldName = "series";
var newValue = "";

var fieldID = Zotero.ItemFields.getID(fieldName);
var s = new Zotero.Search();
s.libraryID = ZoteroPane.getSelectedLibraryID();
var ids = await s.search();
if (!ids.length) {
return "No items found";
}
await Zotero.DB.executeTransaction(async function () {
for (let id of ids) {
let item = await Zotero.Items.getAsync(id);
let mappedFieldID = Zotero.ItemFields.getFieldIDFromTypeAndBase(item.itemTypeID, fieldName);
var IF=impact_factors[item.getField('publicationTitle').toLowerCase()]
item.setField(mappedFieldID ? mappedFieldID : fieldID, newValue);
if(IF!=undefined){
    item.setField('series',IF)
}

await item.save();
}
});
return ids.length + " item(s) IF updated, and shown in series field!";
