var impact_factors={
"2d materials":4.5,
"3d printing and additive manufacturing":2.3,
"aatcc review":0.1,
"academy of management annals":14.3,
"academy of management journal":9.5,
"academy of management review":19.3,
"accounts of chemical research":16.4,
"accounts of materials research":14,
"aci materials journal":1.9,
"aci structural journal":1.3,
"acm computing surveys":23.8,
"acs applied bio materials":4.6,
"acs applied electronic materials":4.3,
"acs applied energy materials":5.4,
"acs applied materials & interfaces":8.3,
"acs applied nano materials":5.3,
"acs applied polymer materials":4.4,
"acs biomaterials science & engineering":5.4,
"acs catalysis":11.3,
"acs central science":12.7,
"acs earth and space chemistry":2.9,
"acs energy letters":19.3,
"acs engineering au":4.3,
"acs environmental au":0.68,
"acs es&t engineering":0.72,
"acs es&t water":1.04,
"acs macro letters":5.1,
"acs materials au":5.7,
"acs materials letters":9.6,
"acs nano":15.8,
"acs omega":3.7,
"acs organic & inorganic au":3.3,
"acs photonics":6.6,
"acs polymers au":4.7,
"acs sensors":8.2,
"acs sustainable chemistry & engineering":7.1,
"acta biomaterialia":9.4,
"acta chemica iasi":0.4,
"acta chimica sinica":1.7,
"acta chimica slovaca":0.9,
"acta chimica slovenica":1.2,
"acta crystallographica a-foundation and advances":1.9,
"acta crystallographica section b-structural science crystal engineering and materials":1.3,
"acta crystallographica section c-structural chemistry":0.7,
"acta facultatis xylologiae zvolen":0.9,
"acta materialia":8.4,
"acta mechanica solida sinica":2,
"acta neuropathologica":9.3,
"acta numerica":16.3,
"acta pharmaceutica sinica b":14.7,
"acta pharmacologica sinica":6.9,
"acta physico-chimica sinica":10.8,
"acta polymerica sinica":1.7,
"acta scientiarum polonorum-formatio circumiectus":0.13,
"additive manufacturing":10.3,
"additive manufacturing letters":4.2,
"adsorption science & technology":2.8,
"adsorption-journal of the international adsorption society":3,
"advanced biology":3.2,
"advanced composite materials":1.8,
"advanced composites and hybrid materials":23.2,
"advanced drug delivery reviews":15.2,
"advanced electronic materials":5.3,
"advanced energy and sustainability research":6.2,
"advanced energy materials":24.4,
"advanced engineering materials":3.4,
"advanced fiber materials":17.2,
"advanced functional materials":18.5,
"advanced healthcare materials":10,
"advanced industrial and engineering polymer research":9.9,
"advanced materials":27.4,
"advanced materials & processes":0.8,
"advanced materials interfaces":4.3,
"advanced materials technologies":6.5,
"advanced nanobiomed research":4,
"advanced optical materials":8.1,
"advanced photonics":20.6,
"advanced photonics research":3.7,
"advanced powder materials":28.6,
"advanced powder technology":4.2,
"advanced science":14.3,
"advanced steel construction":1.7,
"advanced sustainable systems":6.5,
"advances in applied energy":13,
"advances in cement research":1.4,
"advances in civil engineering materials":1.4,
"advances in climate change research":1.25,
"advances in colloid and interface science":15.9,
"advances in concrete construction":2.2,
"advances in environmental research-an international journal":0.05,
"advances in manufacturing":4.2,
"advances in materials and processing technologies":2,
"advances in materials research-an international journal":1.9,
"advances in materials science":1.5,
"advances in methods and practices in psychological science":15.6,
"advances in nano research":4.3,
"advances in natural sciences-nanoscience and nanotechnology":1.7,
"advances in optics and photonics":25.2,
"advances in physics":35,
"advances in polymer technology":2,
"advances in production engineering & management":2.8,
"aerobiologia":0.44,
"aerosol and air quality research":0.68,
"aerosol science and engineering":0.3,
"aerosol science and technology":2.8,
"afinidad":0.2,
"african journal of range & forage science":0.41,
"ageing research reviews":12.5,
"aggregate":13.9,
"agricultural & environmental letters":0.5,
"agriculture ecosystems & environment":1.72,
"aiche journal":3.5,
"aims environmental science":0.3,
"aims materials science":1.4,
"aip advances":1.4,
"air quality atmosphere and health":0.73,
"air soil and water research":0.59,
"allergy":12.6,
"alzheimers & dementia":13,
"ambio":0.81,
"american economic review":10.5,
"american journal of bioethics":17,
"american journal of hematology":10.1,
"american journal of kidney diseases":9.4,
"american journal of psychiatry":15.1,
"american journal of public health":9.6,
"american journal of respiratory and critical care medicine":19.3,
"american psychologist":12.3,
"analytic methods in accident research":12.5,
"anesthesiology":9.1,
"angewandte chemie-international edition":16.1,
"angiogenesis":9.2,
"annales de chimie-science des materiaux":0.6,
"annali di botanica":0.33,
"annals of agricultural and environmental medicine":0.31,
"annals of internal medicine":19.6,
"annals of oncology":56.7,
"annals of regional science":0.55,
"annals of the rheumatic diseases":20.3,
"annals of tourism research":10.4,
"annual review of astronomy and astrophysics":26.3,
"annual review of biochemistry":12.1,
"annual review of biomedical engineering":12.8,
"annual review of biophysics":10.4,
"annual review of cell and developmental biology":11.4,
"annual review of chemical and biomolecular engineering":7.6,
"annual review of clinical psychology":17.8,
"annual review of condensed matter physics":14.3,
"annual review of control robotics and autonomous systems":11.2,
"annual review of earth and planetary sciences":11.3,
"annual review of ecology evolution and systematics":11.2,
"annual review of entomology":15,
"annual review of environment and resources":15.5,
"annual review of fluid mechanics":25.4,
"annual review of food science and technology":10.6,
"annual review of immunology":26.9,
"annual review of marine science":14.3,
"annual review of materials research":10.6,
"annual review of medicine":15.1,
"annual review of neuroscience":12.1,
"annual review of nuclear and particle science":9.1,
"annual review of nutrition":12.6,
"annual review of organizational psychology and organizational behavior":14.3,
"annual review of pathology-mechanisms of disease":28.4,
"annual review of pharmacology and toxicology":11.2,
"annual review of physical chemistry":11.7,
"annual review of physiology":15.7,
"annual review of plant biology":21.3,
"annual review of political science":9.7,
"annual review of psychology":23.6,
"annual review of public health":21.4,
"annual review of resource economics":1.59,
"antarctic science":0.4,
"anthropocene":0.86,
"anthropocene coasts":0.59,
"anthropocene review":0.43,
"apl materials":5.3,
"applications in energy and combustion science":5,
"applied catalysis a-general":0.83,
"applied catalysis b-environment and energy":20.2,
"applied chemistry for engineering":0.4,
"applied clay science":5.4,
"applied composite materials":2.3,
"applied computing and informatics":12.3,
"applied ecology and environmental research":0.15,
"applied energy":10.1,
"applied materials today":7.4,
"applied mechanics reviews":12.2,
"applied physics a-materials science & processing":2.5,
"applied physics reviews":11.9,
"applied science and convergence technology":1.2,
"applied sciences-basel":2.5,
"applied spatial analysis and policy":0.53,
"applied surface science":6.3,
"applied surface science advances":7.5,
"aquatic conservation-marine and freshwater ecosystems":0.67,
"aquatic ecosystem health & management":0.22,
"aquatic sciences":0.65,
"arabian journal of chemistry":5.3,
"archiv der pharmazie":4.3,
"archives of civil and mechanical engineering":4.4,
"archives of computational methods in engineering":9.7,
"archives of environmental & occupational health":0.37,
"archives of environmental contamination and toxicology":0.73,
"archives of environmental protection":0.26,
"archives of mechanics":1.1,
"arctic":0.24,
"arctic antarctic and alpine research":0.37,
"arctic science":0.75,
"arid land research and management":0.36,
"arthritis & rheumatology":11.4,
"artificial cells nanomedicine and biotechnology":4.6,
"artificial intelligence review":10.7,
"asia pacific journal of environmental law":0.29,
"asian journal of pharmaceutical sciences":10.7,
"asian journal of water environment and pollution":0.08,
"asia-pacific journal of chemical engineering":1.4,
"asia-pacific journal of regional science":0.45,
"astronomy and astrophysics review":27.8,
"atmosphere":0.56,
"atmospheric chemistry and physics":1.23,
"atmospheric environment":0.97,
"atmospheric environment-x":0.84,
"atmospheric pollution research":0.82,
"atomization and sprays":1,
"australasian journal of environmental management":0.26,
"australian journal of chemistry":1,
"autism in adulthood":9.5,
"autoimmunity reviews":9.2,
"automation in construction":9.6,
"autophagy":14.6,
"batteries & supercaps":5.1,
"batteries-basel":4.6,
"battery energy":9,
"behavioral and brain sciences":16.6,
"beilstein journal of nanotechnology":2.6,
"beton- und stahlbetonbau":1,
"bioactive materials":18,
"biochar":13.1,
"biochemical engineering journal":3.7,
"biochimica et biophysica acta-reviews on cancer":9.7,
"bioconjugate chemistry":4,
"biodiversity and conservation":0.71,
"bioenergy research":0.53,
"biofabrication":8.3,
"biofuel research journal-brj":14.4,
"biogeochemistry":0.89,
"bioinspiration & biomimetics":3.2,
"bioinspired biomimetic and nanobiomaterials":1.4,
"biointerphases":1.7,
"biological conservation":1.32,
"biological psychiatry":9.6,
"biological reviews":11,
"biology and environment-proceedings of the royal irish academy":0.12,
"biomacromolecules":5.5,
"biomarker research":9.5,
"biomass conversion and biorefinery":3.5,
"biomaterials":12.8,
"biomaterials advances":5.5,
"biomaterials research":8.1,
"biomaterials science":5.8,
"biomedical and environmental sciences":0.53,
"biomedical materials":3.9,
"bio-medical materials and engineering":1,
"biomimetics":3.4,
"bionanoscience":3,
"bioprocess and biosystems engineering":3.5,
"bioremediation journal":0.26,
"bioresource technology":9.7,
"bioresources":1.3,
"biosensors & bioelectronics":10.7,
"biosurface and biotribology":1.6,
"biotechnologie agronomie societe et environnement":0.14,
"biotechnology advances":12.1,
"blood":21,
"blood cancer discovery":11.5,
"blood cancer journal":12.9,
"blue-green systems":0.7,
"bmc chemistry":4.3,
"bmj-british medical journal":93.6,
"boletin del grupo espanol del carbon":0.1,
"bone research":14.3,
"boreal environment research":0.22,
"brain":10.6,
"brazilian journal of chemical engineering":1.5,
"british journal of anaesthesia":9.1,
"british journal of dermatology":11,
"british journal of sports medicine":11.6,
"building and environment":1.24,
"bulgarian journal of agricultural science":0.07,
"bulletin of chemical reaction engineering and catalysis":1.3,
"bulletin of engineering geology and the environment":0.86,
"bulletin of environmental contamination and toxicology":0.59,
"bulletin of materials science":1.9,
"bulletin of the chemical society of ethiopia":1.3,
"bulletin of the chemical society of japan":3.3,
"bulletin of the korean chemical society":2.3,
"bulletin of the university of karaganda-chemistry":0.6,
"business strategy and development":0.67,
"business strategy and the environment":12.5,
"ca-a cancer journal for clinicians":503.1,
"cailiao gongcheng-journal of materials engineering":0.6,
"calphad-computer coupling of phase diagrams and thermochemistry":1.9,
"canadian journal of chemical engineering":1.6,
"canadian journal of chemistry":1.1,
"canadian medical association journal":9.4,
"cancer cell":48.8,
"cancer communications":20.1,
"cancer discovery":29.7,
"cancer letters":9.1,
"cancer research":12.5,
"cancer treatment reviews":9.6,
"carbohydrate polymer technologies and applications":6.2,
"carbohydrate polymers":10.7,
"carbon":10.5,
"carbon balance and management":0.65,
"carbon capture science & technology":10.4,
"carbon energy":19.5,
"carbon letters":5.5,
"carbon management":0.55,
"carbon resources conversion":6.4,
"carbon trends":3.1,
"cardiovascular research":10.2,
"carpathian journal of earth and environmental sciences":0.23,
"case studies in construction materials":6.5,
"case studies in the environment":0.27,
"catalysis in industry":0.7,
"catalysis reviews-science and engineering":9.3,
"catalysis today":5.2,
"catrina-the international journal of environmental sciences":0.05,
"ccs chemistry":9.4,
"cell":45.5,
"cell death and differentiation":13.7,
"cell discovery":13,
"cell genomics":11.1,
"cell host & microbe":20.6,
"cell metabolism":27.7,
"cell reports medicine":11.7,
"cell reports physical science":8,
"cell research":28.1,
"cell stem cell":19.8,
"cellular & molecular biology letters":9.2,
"cellular & molecular immunology":21.8,
"cellular polymers":1.3,
"cellulose":4.9,
"cellulose chemistry and technology":1.3,
"cement & concrete composites":10.8,
"cement and concrete research":10.9,
"cement wapno beton":0.5,
"central european journal of energetic materials":0.7,
"ceramics-switzerland":2.7,
"chalcogenide letters":1.2,
"chem":19.1,
"chem catalysis":11.5,
"chembioeng reviews":6.2,
"chemengineering":2.8,
"chemical & pharmaceutical bulletin":1.5,
"chemical and biochemical engineering quarterly":1.6,
"chemical and petroleum engineering":0.3,
"chemical and process engineering-new frontiers":0.5,
"chemical bulletin of kazakh national university":0.3,
"chemical communications":4.3,
"chemical engineering & technology":1.8,
"chemical engineering and processing-process intensification":3.8,
"chemical engineering communications":1.9,
"chemical engineering journal":13.3,
"chemical engineering journal advances":5.5,
"chemical engineering research & design":3.7,
"chemical engineering science":4.1,
"chemical industry & chemical engineering quarterly":1,
"chemical journal of chinese universities-chinese":0.7,
"chemical methodologies":3.5,
"chemical papers":2.1,
"chemical product and process modeling":1,
"chemical record":7,
"chemical research in chinese universities":3.1,
"chemical research in toxicology":3.7,
"chemical reviews":51.4,
"chemical science":7.6,
"chemical society reviews":40.4,
"chemicke listy":0.6,
"chemie in unserer zeit":0.9,
"chemie ingenieur technik":1.5,
"chemija":0.5,
"chemistry & biodiversity":2.3,
"chemistry & chemical technology":1,
"chemistry africa-a journal of the tunisian chemical society":2.3,
"chemistry and ecology":0.41,
"chemistry and technology of fuels and oils":0.6,
"chemistry for sustainable development":0.4,
"chemistry journal of moldova":0.5,
"chemistry letters":1.4,
"chemistry of materials":7.2,
"chemistry-a european journal":3.9,
"chemistry-an asian journal":3.5,
"chemistrymethods":6.1,
"chemistryopen":2.5,
"chemistryselect":1.9,
"chemistry-switzerland":2.4,
"chemnanomat":2.6,
"chemosphere":1.58,
"chempluschem":3,
"chemsuschem":7.5,
"chemsystemschem":3.1,
"chemtexts":2.9,
"chest":9.5,
"chimia":1.1,
"china petroleum processing & petrochemical technology":0.6,
"china surface engineering":0.8,
"chinese chemical letters":9.4,
"chinese geographical science":0.64,
"chinese journal of catalysis":15.7,
"chinese journal of chemical engineering":3.7,
"chinese journal of chemistry":5.5,
"chinese journal of environmental law":0.29,
"chinese journal of polymer science":4.1,
"chinese journal of population resources and environment":0.59,
"circuit world":0.8,
"circulation":35.5,
"circulation research":16.5,
"circulation-arrhythmia and electrophysiology":9.1,
"city and environment interactions":0.73,
"c-journal of carbon research":3.9,
"clean energy":0.35,
"clean technologies":0.49,
"clean technologies and environmental policy":0.59,
"cleaner and responsible consumption":0.63,
"cleaner engineering and technology":0.7,
"cleaner environmental systems":0.92,
"clean-soil air water":0.34,
"climate and development":0.79,
"climate change economics":1.14,
"climate law":0.76,
"climate policy":1.67,
"climate research":0.28,
"climate risk management":1.05,
"climate services":0.8,
"climatic change":0.93,
"clinical and molecular hepatology":14,
"clinical cancer research":10,
"clinical gastroenterology and hepatology":11.6,
"clinical microbiology and infection":10.9,
"clinical microbiology reviews":19,
"clinical nuclear medicine":9.6,
"clinical psychology review":13.7,
"cmc-computers materials & continua":2.1,
"coastal management":0.46,
"coatings":2.9,
"coke and chemistry":0.4,
"cold regions science and technology":0.76,
"colloid and interface science communications":4.7,
"colloid and polymer science":2.2,
"colloids and surfaces b-biointerfaces":5.4,
"coloration technology":2,
"combustion and flame":5.8,
"combustion explosion and shock waves":0.9,
"combustion science and technology":1.7,
"combustion theory and modelling":1.9,
"communications chemistry":5.9,
"communications earth & environment":1.85,
"communications in transportation research":12.5,
"communications materials":7.6,
"communications of the acm":11.1,
"composite interfaces":2.1,
"composite structures":6.3,
"composites and advanced materials":1.7,
"composites communications":6.5,
"composites part a-applied science and manufacturing":8.2,
"composites part b-engineering":12.7,
"composites part c: open access":5.3,
"composites research":0.5,
"composites science and technology":8.3,
"composites theory and practice":0.5,
"comprehensive reviews in food science and food safety":12,
"comptes rendus chimie":1.2,
"computational materials science":3.1,
"computational visual media":17.3,
"computer science review":13.3,
"computers & chemical engineering":3.9,
"computers and concrete":3,
"computers environment and urban systems":1.49,
"conservation & society":0.44,
"conservation biology":1.33,
"conservation physiology":0.73,
"construction and building materials":7.4,
"coordination chemistry reviews":20.3,
"corporate social responsibility and environmental management":1.87,
"corrosion":1.1,
"corrosion engineering science and technology":1.5,
"corrosion reviews":2.7,
"corrosion science":7.5,
"critical reviews in environmental science and technology":11.4,
"critical reviews in solid state and materials sciences":8.1,
"croatica chemica acta":0.7,
"crystal growth & design":3.3,
"crystals":2.4,
"crystengcomm":2.6,
"cultural geographies":0.45,
"current applied physics":2.4,
"current climate change reports":9.3,
"current green chemistry":1.1,
"current microwave chemistry":0.9,
"current nanoscience":1.4,
"current obesity reports":9.5,
"current opinion in chemical engineering":8,
"current opinion in electrochemistry":7.9,
"current opinion in environmental science & health":1.64,
"current opinion in environmental sustainability":1.02,
"current opinion in green and sustainable chemistry":9.3,
"current opinion in solid state & materials science":12.2,
"current pollution reports":1.33,
"current research in environmental sustainability":0.81,
"cyborg and bionic systems":10.5,
"cytokine & growth factor reviews":9.3,
"dental materials":4.7,
"dental materials journal":2,
"desalination":8.3,
"desalination and water treatment":1,
"desenvolvimento e meio ambiente":0.06,
"designed monomers and polymers":1.8,
"detritus":0.13,
"developmental cell":10.7,
"diabetes care":14.8,
"diamond and related materials":4.3,
"digest journal of nanomaterials and biostructures":1,
"digital chemical engineering":3,
"digital discovery":6.2,
"disaster prevention and management":0.45,
"disasters":1.23,
"discover sustainability":0.31,
"doklady chemistry":0.8,
"drewno":0.8,
"drug and chemical toxicology":2.1,
"drug resistance updates":15.8,
"drugs":13,
"drvna industrija":0.7,
"drying technology":2.7,
"dyes and pigments":4.1,
"earth":0.42,
"earth system governance":2.17,
"earth system science data":11.2,
"earth systems and environment":1.36,
"earths future":1.69,
"earth-science reviews":10.8,
"ebiomedicine":9.7,
"eclinicalmedicine":9.6,
"ecohealth":0.56,
"ecohydrology":0.58,
"ecological applications":1.12,
"ecological chemistry and engineering s-chemia i inzynieria ekologiczna s":0.29,
"ecological economics":1.58,
"ecological engineering":0.75,
"ecological indicators":1.65,
"ecological processes":0.95,
"ecology and society":0.86,
"ecology law quarterly":0.32,
"ecomat":10.7,
"economics of energy & environmental policy":0.41,
"ecosystem health and sustainability":0.9,
"ecosystem services":1.42,
"ecosystems and people":0.97,
"ecotoxicology":0.62,
"ecotoxicology and environmental safety":1.47,
"ecs journal of solid state science and technology":1.8,
"education for chemical engineers":3.5,
"educational psychologist":14.3,
"educational psychology review":10.1,
"educational research review":9.6,
"egyptian journal of chemistry":1.1,
"egyptian journal of remote sensing and space sciences":0.81,
"ekonomia i srodowisko-economics and environment":0.14,
"elastomers and composites":1.3,
"electrochemical energy reviews":28.4,
"electronic materials letters":2.1,
"electronic structure":2.9,
"elementa-science of the anthropocene":0.85,
"elight":27.2,
"embo journal":9.4,
"emergent materials":4.8,
"emerging contaminants":1.25,
"emerging materials research":1.3,
"emission control science and technology":1.3,
"endocrine pathology":11.3,
"endocrine reviews":22,
"endoscopy":11.5,
"energetic materials frontiers":3.3,
"energy & environment":0.94,
"energy & environmental materials":13,
"energy & environmental science":32.4,
"energy & fuels":5.2,
"energy advances":3.2,
"energy and ai":9.6,
"energy conversion and management":9.9,
"energy ecology and environment":0.8,
"energy economics":13.6,
"energy efficiency":0.58,
"energy journal":0.55,
"energy material advances":14.8,
"energy materials":11.8,
"energy nexus":1.27,
"energy policy":9.3,
"energy research & social science":1.48,
"energy sources part a-recovery utilization and environmental effects":2.3,
"energy storage materials":18.9,
"energychem":22.2,
"engineering":10.1,
"engineering failure analysis":4.5,
"engineering reports":1.8,
"environment":0.48,
"environment and behavior":1.31,
"environment and development economics":0.59,
"environment and history":1.61,
"environment and planning a-economy and space":1.25,
"environment and planning b-urban analytics and city science":0.78,
"environment and planning c-politics and space":0.7,
"environment and planning d-society & space":0.98,
"environment and planning e-nature and space":1.02,
"environment and society-advances in research":0.38,
"environment and urbanization":0.77,
"environment and urbanization asia":0.29,
"environment development and sustainability":0.8,
"environment international":10.3,
"environment protection engineering":0.06,
"environmental & engineering geoscience":0.19,
"environmental & resource economics":1.23,
"environmental & socio-economic studies":0.21,
"environmental and ecological statistics":1.18,
"environmental and experimental botany":1.17,
"environmental and molecular mutagenesis":0.51,
"environmental and sustainability indicators":0.88,
"environmental chemistry":0.39,
"environmental chemistry and ecotoxicology":1.67,
"environmental chemistry letters":15,
"environmental communication-a journal of nature and culture":0.92,
"environmental conservation":0.49,
"environmental development":0.87,
"environmental earth sciences":0.67,
"environmental education research":1.04,
"environmental engineering and management journal":0.17,
"environmental engineering research":0.47,
"environmental engineering science":0.25,
"environmental epidemiology":0.78,
"environmental ethics":0.21,
"environmental evidence":0.53,
"environmental fluid mechanics":0.51,
"environmental forensics":0.29,
"environmental geochemistry and health":0.78,
"environmental hazards-human and policy dimensions":0.61,
"environmental health":1.2,
"environmental health engineering and management journal":0.26,
"environmental health perspectives":10.1,
"environmental history":1.14,
"environmental impact assessment review":9.8,
"environmental innovation and societal transitions":1.26,
"environmental justice":0.3,
"environmental management":0.55,
"environmental microbiology reports":0.58,
"environmental modeling & assessment":0.5,
"environmental modelling & software":0.91,
"environmental monitoring and assessment":0.57,
"environmental policy and governance":0.67,
"environmental politics":1.67,
"environmental pollutants and bioavailability":0.63,
"environmental pollution":1.5,
"environmental processes-an international journal":0.41,
"environmental progress & sustainable energy":2.1,
"environmental quality management":0.35,
"environmental research":1.98,
"environmental research communications":0.51,
"environmental research letters":1.21,
"environmental research: infrastructure and sustainability":0.46,
"environmental reviews":0.38,
"environmental science & policy":1,
"environmental science & technology":10.8,
"environmental science & technology letters":1.49,
"environmental science and ecotechnology":14,
"environmental science and pollution research":0.99,
"environmental science-advances":0.54,
"environmental science-atmospheres":0.65,
"environmental science-nano":5.8,
"environmental science-processes & impacts":0.83,
"environmental sciences europe":1,
"environmental science-water research & technology":0.68,
"environmental sociology":0.57,
"environmental sustainability":0.27,
"environmental technology":0.46,
"environmental technology & innovation":1.24,
"environmental toxicology":1.07,
"environmental toxicology and chemistry":0.78,
"environmental toxicology and pharmacology":1.05,
"environmental values":0.87,
"environments":0.6,
"environmetrics":0.57,
"epitoanyag-journal of silicate based and composite materials":0.5,
"epj applied metamaterials":1.5,
"e-polymers":3.2,
"eqa-international journal of environmental quality":0.11,
"escience":42.9,
"estuaries and coasts":0.68,
"ethics policy & environment":0.28,
"etransportation":15,
"eurasian chemico-technological journal":0.5,
"euro-mediterranean journal for environmental integration":0.32,
"european cells & materials":3.2,
"european heart journal":37.6,
"european journal of environmental sciences":0.11,
"european journal of heart failure":16.9,
"european journal of sustainable development":0.16,
"european journal of wood and wood products":2.4,
"european physical journal e":1.8,
"european planning studies":0.74,
"european polymer journal":5.8,
"european respiratory journal":16.6,
"european review of social psychology":10.1,
"european urban and regional studies":0.73,
"european urology":25.3,
"eurosurveillance":9.9,
"experimental and molecular medicine":9.5,
"experimental hematology & oncology":9.4,
"experimental mechanics":2,
"experimental techniques":1.6,
"express polymer letters":2.7,
"extractive industries and society":0.74,
"extreme mechanics letters":4.4,
"facta universitatis-series mechanical engineering":10.1,
"family business review":9.9,
"fatigue & fracture of engineering materials & structures":3.1,
"fdmp-fluid dynamics & materials processing":0.8,
"fems microbiology reviews":10.1,
"ferroelectrics":0.6,
"fibers":4,
"fibers and polymers":2.2,
"fibre chemistry":0.5,
"filtration + separation":0.1,
"fire and materials":2,
"fire safety journal":3.4,
"fire technology":2.4,
"flatchem":6,
"flexible and printed electronics":2.8,
"fluid phase equilibria":2.8,
"food and bioproducts processing":3.5,
"food and environmental virology":0.68,
"food hydrocolloids":11,
"forces in mechanics":3.2,
"forest policy and economics":1.27,
"forest products journal":1.1,
"forests trees and livelihoods":0.32,
"foundations and trends in machine learning":65.3,
"frattura ed integrita strutturale-fracture and structural integrity":1.2,
"frontiers in chemical engineering":2.5,
"frontiers in chemistry":3.8,
"frontiers in climate":0.62,
"frontiers in conservation science":0.4,
"frontiers in ecology and the environment":10,
"frontiers in environmental science":0.67,
"frontiers in materials":2.6,
"frontiers in nanotechnology":4.1,
"frontiers in sustainable cities":0.45,
"frontiers of chemical science and engineering":4.3,
"frontiers of environmental science & engineering":0.97,
"frontiers of materials science":2.5,
"fuel":6.7,
"fuel processing technology":7.2,
"fuels":2.7,
"fullerenes nanotubes and carbon nanostructures":2.1,
"functional composites and structures":3.1,
"functional materials":0.4,
"functional materials letters":1.2,
"fungal diversity":24.5,
"gaia-ecological perspectives for science and society":0.25,
"gastroenterology":25.7,
"gefahrstoffe reinhaltung der luft":0.03,
"gels":5,
"genome biology":10.1,
"genome medicine":10.4,
"genomics proteomics & bioinformatics":11.5,
"geobiology":0.73,
"geocarto international":0.74,
"geoenvironmental disasters":0.82,
"geografisk tidsskrift-danish journal of geography":0.53,
"geohealth":1.01,
"geology geophysics and environment":0.13,
"geomicrobiology journal":0.43,
"geosynthetics international":2.8,
"giant":5.4,
"gigascience":11.8,
"glasnik hemicara i tehnologa bosne i hercegovine":0.2,
"global biogeochemical cycles":1.2,
"global change biology":10.8,
"global environment":0.05,
"global environmental change-human and policy dimensions":2.37,
"global environmental politics":1.76,
"global food security-agriculture policy economics and environment":9.8,
"global journal of environmental science and management-gjesm":0.65,
"global nest journal":0.16,
"global sustainability":0.82,
"gold bulletin":2.1,
"granja-revista de ciencias de la vida":0.09,
"granular matter":2.3,
"green chemical engineering":9.1,
"green chemistry":9.3,
"green chemistry letters and reviews":5.8,
"green energy & environment":10.7,
"green materials":1.8,
"green processing and synthesis":3.8,
"green synthesis and catalysis":8.2,
"greenhouse gases-science and technology":0.3,
"groundwater for sustainable development":0.98,
"grundwasser":0.21,
"gut":23,
"gut microbes":12.2,
"habitat international":1.68,
"hardwarex":2,
"harvard environmental law review":0.29,
"health physics":0.64,
"helvetica chimica acta":1.5,
"hemijska industrija":0.8,
"hepatology":12.9,
"heritage science":2.7,
"heteroatom chemistry":1.1,
"high performance polymers":1.8,
"high temperature material processes":0.7,
"high temperature materials and processes":1.6,
"high temperatures-high pressures":0.4,
"holzforschung":2.2,
"housing studies":0.58,
"housing theory & society":0.64,
"human and ecological risk assessment":0.83,
"human dimensions of wildlife":0.39,
"human ecology":0.83,
"human ecology review":0.18,
"human reproduction update":14.8,
"hungarian journal of industry and chemistry":0.5,
"ieee communications surveys and tutorials":34.4,
"ieee computational intelligence magazine":10.3,
"ieee geoscience and remote sensing magazine":16.2,
"ieee journal of photovoltaics":2.5,
"ieee journal on selected areas in communications":13.8,
"ieee open journal of nanotechnology":1.8,
"ieee reviews in biomedical engineering":17.2,
"ieee signal processing magazine":9.4,
"ieee transactions on affective computing":9.6,
"ieee transactions on components packaging and manufacturing technology":2.3,
"ieee transactions on cybernetics":9.4,
"ieee transactions on evolutionary computation":11.7,
"ieee transactions on fuzzy systems":10.7,
"ieee transactions on image processing":10.8,
"ieee transactions on industrial informatics":11.7,
"ieee transactions on intelligent vehicles":14,
"ieee transactions on nanotechnology":2.1,
"ieee transactions on neural networks and learning systems":10.2,
"ieee transactions on pattern analysis and machine intelligence":20.8,
"ieee transactions on robotics":9.4,
"ieee wireless communications":10.9,
"ieee-caa journal of automatica sinica":15.3,
"iet nanodielectrics":3.8,
"image analysis & stereology":0.8,
"imeta":23.7,
"immunity":25.5,
"impact assessment and project appraisal":0.41,
"indian chemical engineer":0.9,
"indian journal of chemical technology":0.5,
"indian journal of engineering and materials sciences":0.7,
"indonesian journal of chemistry":1,
"indoor air":0.9,
"indoor and built environment":0.53,
"industrial & engineering chemistry research":3.8,
"industrial and organizational psychology-perspectives on science and practice":11.5,
"industrial health":0.45,
"infomat":22.7,
"informacije midem-journal of microelectronics electronic components and materials":0.7,
"information fusion":14.7,
"innovation":33.2,
"inorganic materials":0.9,
"inorganic materials-applied research":0.5,
"insight":1,
"integrated environmental assessment and management":0.62,
"integrating materials and manufacturing innovation":2.4,
"intensive care medicine":27.1,
"interdisciplinary materials":24.5,
"intermetallics":4.3,
"international biodeterioration & biodegradation":0.91,
"international environmental agreements-politics law and economics":1.51,
"international journal for numerical and analytical methods in geomechanics":3.4,
"international journal of adhesion and adhesives":3.2,
"international journal of biological macromolecules":7.7,
"international journal of biomaterials":3,
"international journal of biometeorology":0.74,
"international journal of bioprinting":6.8,
"international journal of chemical engineering":2.3,
"international journal of chemical reactor engineering":1.2,
"international journal of climate change strategies and management":0.75,
"international journal of computational materials science and engineering":1.4,
"international journal of computer vision":11.6,
"international journal of concrete structures and materials":3.6,
"international journal of contemporary hospitality management":9.1,
"international journal of corrosion and scale inhibition":2.8,
"international journal of damage mechanics":4,
"international journal of disaster resilience in the built environment":0.26,
"international journal of energetic materials and chemical propulsion":0.5,
"international journal of environment and pollution":0.05,
"international journal of environment and sustainable development":0.15,
"international journal of environment and waste management":0.07,
"international journal of environmental analytical chemistry":0.53,
"international journal of environmental health research":0.55,
"international journal of environmental research":0.54,
"international journal of environmental science and technology":0.52,
"international journal of environmental technology and management":0.05,
"international journal of extreme manufacturing":16.1,
"international journal of fatigue":5.8,
"international journal of fracture":2.2,
"international journal of global energy issues":0.11,
"international journal of global warming":0.19,
"international journal of greenhouse gas control":4.6,
"international journal of hospitality management":9.9,
"international journal of housing policy":0.6,
"international journal of hydrology science and technology":0.24,
"international journal of information management":20.1,
"international journal of life cycle assessment":0.65,
"international journal of machine tools & manufacture":14,
"international journal of material forming":2.6,
"international journal of materials & product technology":0.5,
"international journal of mechanical and materials engineering":3.4,
"international journal of mechanics and materials in design":2.7,
"international journal of minerals metallurgy and materials":5.7,
"international journal of mining reclamation and environment":0.74,
"international journal of mining science and technology":11.7,
"international journal of molecular sciences":4.9,
"international journal of nanoelectronics and materials":0.7,
"international journal of nanotechnology":0.3,
"international journal of oil gas and coal technology":0.6,
"international journal of oral science":10.8,
"international journal of pavement engineering":3.5,
"international journal of pavement research and technology":3,
"international journal of phytoremediation":0.62,
"international journal of plasticity":9.4,
"international journal of polymer analysis and characterization":1.7,
"international journal of polymer science":3.4,
"international journal of polymeric materials and polymeric biomaterials":2.5,
"international journal of production economics":9.8,
"international journal of recycling of organic waste in agriculture":0.23,
"international journal of refractory metals & hard materials":4.2,
"international journal of sediment research":0.85,
"international journal of self-propagating high-temperature synthesis":0.5,
"international journal of smart and nano materials":4.5,
"international journal of surface science and engineering":1,
"international journal of surgery":12.5,
"international journal of sustainable transportation":0.67,
"international journal of the commons":0.39,
"international journal of transgender health":10.5,
"international journal of urban sciences":0.71,
"international journal of urban sustainable development":0.46,
"international materials reviews":16.8,
"international polymer processing":1.1,
"international regional science review":0.49,
"international soil and water conservation research":1.59,
"international wood products journal":1.3,
"iranian journal of chemistry & chemical engineering-international english edition":1,
"iranian journal of materials science and engineering":1.1,
"iranian journal of mathematical chemistry":1,
"iranian polymer journal":2.4,
"isme journal":10.8,
"isotopes in environmental and health studies":0.31,
"isprs journal of photogrammetry and remote sensing":10.6,
"israel journal of chemistry":2.3,
"italian journal of agrometeorology-rivista italiana di agrometeorologia":0.3,
"iucrj":2.9,
"izvestiya vuzov-prikladnaya khimiya i biotekhnologiya":0.2,
"izvestiya vysshikh uchebnykh zavedenii khimiya i khimicheskaya tekhnologiya":0.6,
"jacc: cardiooncology":12,
"jacc-cardiovascular imaging":12.8,
"jacc-cardiovascular interventions":11.7,
"jacc-heart failure":10.3,
"jacs au":8.5,
"jama cardiology":14.8,
"jama dermatology":11.5,
"jama health forum":9.5,
"jama internal medicine":22.5,
"jama network open":10.5,
"jama neurology":20.4,
"jama oncology":22.5,
"jama pediatrics":24.7,
"jama psychiatry":22.5,
"jama surgery":15.7,
"jama-journal of the american medical association":63.1,
"jhep reports":9.5,
"jnci-journal of the national cancer institute":9.9,
"jom":2.1,
"jordan journal of chemistry":0.4,
"joule":38.6,
"journal for immunotherapy of cancer":10.3,
"journal of adhesion":2.9,
"journal of adhesion science and technology":2.7,
"journal of advanced ceramics":18.6,
"journal of advanced concrete technology":1.6,
"journal of advanced joining processes":3.8,
"journal of advanced research":11.4,
"journal of aerosol science":3.9,
"journal of agricultural & environmental ethics":0.88,
"journal of agricultural education & extension":0.92,
"journal of allergy and clinical immunology":11.4,
"journal of alloys and compounds":5.9,
"journal of analytical and applied pyrolysis":5.8,
"journal of applied biomaterials & functional materials":3.1,
"journal of applied crystallography":5.2,
"journal of applied polymer science":2.7,
"journal of applied psychology":9.4,
"journal of applied remote sensing":0.29,
"journal of arid environments":0.64,
"journal of arid land":0.54,
"journal of atmospheric chemistry":0.56,
"journal of bioactive and compatible polymers":2.1,
"journal of biomaterials applications":2.3,
"journal of biomaterials science-polymer edition":3.6,
"journal of biomedical materials research part a":3.9,
"journal of biomedical materials research part b-applied biomaterials":3.2,
"journal of bionic engineering":4.9,
"journal of bioresources and bioproducts":20.2,
"journal of business logistics":11.2,
"journal of business research":10.5,
"journal of cachexia sarcopenia and muscle":9.4,
"journal of catalysis":6.5,
"journal of cellular plastics":3.2,
"journal of chemical and engineering data":2,
"journal of chemical education":2.5,
"journal of chemical engineering of japan":0.6,
"journal of chemical information and modeling":5.6,
"journal of chemical research":1,
"journal of chemical sciences":1.7,
"journal of chemical technology and biotechnology":2.8,
"journal of cheminformatics":7.1,
"journal of chemistry":2.8,
"journal of chemistry and technologies":0.5,
"journal of cleaner production":9.7,
"journal of clinical investigation":13.3,
"journal of clinical oncology":42.1,
"journal of co2 utilization":7.2,
"journal of coastal conservation":0.48,
"journal of coatings technology and research":2.3,
"journal of cold regions engineering":0.3,
"journal of colloid and interface science":9.4,
"journal of combustion":1.5,
"journal of composite materials":2.3,
"journal of composites for construction":2.9,
"journal of composites science":3,
"journal of computational biophysics and chemistry":2,
"journal of computational chemistry":3.4,
"journal of computer chemistry-japan":0.1,
"journal of contaminant hydrology":0.87,
"journal of controlled release":10.5,
"journal of crystal growth":1.7,
"journal of cultural heritage":3.6,
"journal of dynamic behavior of materials":1.2,
"journal of ecohydraulics":1.18,
"journal of ecological engineering":0.15,
"journal of econometrics":9.9,
"journal of economic literature":11.5,
"journal of educational evaluation for health professions":9.3,
"journal of elasticity":1.8,
"journal of elastomers and plastics":1.4,
"journal of electronic materials":2.2,
"journal of elementology":0.14,
"journal of energetic materials":1.7,
"journal of energy & natural resources law":1.07,
"journal of energy chemistry":14,
"journal of engineering materials and technology-transactions of the asme":1.5,
"journal of environment & development":0.57,
"journal of environmental biology":0.12,
"journal of environmental chemical engineering":7.4,
"journal of environmental economics and management":1.26,
"journal of environmental economics and policy":0.49,
"journal of environmental education":0.98,
"journal of environmental engineering":0.32,
"journal of environmental engineering and landscape management":0.2,
"journal of environmental engineering and science":0.09,
"journal of environmental health":0.12,
"journal of environmental health science and engineering":0.42,
"journal of environmental informatics":1.39,
"journal of environmental law":0.96,
"journal of environmental management":1.49,
"journal of environmental psychology":1.88,
"journal of environmental quality":0.43,
"journal of environmental radioactivity":0.38,
"journal of environmental science and health part a-toxic/hazardous substances & environmental engineering":0.3,
"journal of environmental science and health part b-pesticides food contaminants and agricultural wastes":0.43,
"journal of environmental science and health part c-toxicology and carcinogenesis":0.4,
"journal of environmental science and management":0.07,
"journal of environmental sciences":1.37,
"journal of environmental studies and sciences":0.38,
"journal of experimental & clinical cancer research":11.4,
"journal of experimental medicine":12.6,
"journal of experimental nanoscience":2.6,
"journal of exposure science and environmental epidemiology":1.03,
"journal of extracellular vesicles":15.5,
"journal of family business strategy":9.5,
"journal of fiber science and technology":0.3,
"journal of financial economics":10.4,
"journal of fire sciences":1.9,
"journal of flood risk management":0.74,
"journal of flow chemistry":2,
"journal of food engineering":5.3,
"journal of food process engineering":2.7,
"journal of friction and wear":0.5,
"journal of functional biomaterials":5,
"journal of geophysical research-biogeosciences":0.82,
"journal of geovisualization and spatial analysis":1.28,
"journal of great lakes research":0.75,
"journal of hazardous materials":12.2,
"journal of hazardous materials advances":0.74,
"journal of hazardous materials letters":0.83,
"journal of hazardous toxic and radioactive waste":0.25,
"journal of health population and nutrition":0.55,
"journal of hematology & oncology":29.5,
"journal of hepatology":26.8,
"journal of high energy astrophysics":10.2,
"journal of hospitality marketing & management":11.9,
"journal of housing and the built environment":0.43,
"journal of human rights and the environment":1.65,
"journal of hydro-environment research":0.56,
"journal of hydroinformatics":0.59,
"journal of hydrologic engineering":0.48,
"journal of inclusion phenomena and macrocyclic chemistry":1.7,
"journal of industrial and engineering chemistry":5.9,
"journal of industrial ecology":0.79,
"journal of industrial information integration":10.4,
"journal of infection":14.3,
"journal of information display":3.7,
"journal of innovation & knowledge":15.6,
"journal of inorganic and organometallic polymers and materials":3.9,
"journal of integrative environmental sciences":0.42,
"journal of integrative plant biology":9.3,
"journal of intelligent material systems and structures":2.4,
"journal of international financial management & accounting":9.4,
"journal of laser applications":1.7,
"journal of laser micro nanoengineering":0.8,
"journal of loss prevention in the process industries":3.6,
"journal of macromolecular science part a-pure and applied chemistry":2.1,
"journal of macromolecular science part b-physics":1.2,
"journal of magnesium and alloys":15.8,
"journal of magnetics":0.6,
"journal of magnetism and magnetic materials":2.5,
"journal of management":9.3,
"journal of manufacturing and materials processing":3.3,
"journal of manufacturing systems":12.2,
"journal of marketing":11.5,
"journal of material cycles and waste management":0.51,
"journal of materials chemistry a":10.7,
"journal of materials chemistry b":6.1,
"journal of materials chemistry c":5.7,
"journal of materials engineering and performance":2.2,
"journal of materials in civil engineering":3.1,
"journal of materials processing technology":6.8,
"journal of materials research":2.7,
"journal of materials research and technology-jmr&t":6.3,
"journal of materials science":3.5,
"journal of materials science & technology":11.2,
"journal of materials science-materials in electronics":2.8,
"journal of materials science-materials in medicine":4.2,
"journal of materiomics":8.4,
"journal of mathematical chemistry":1.7,
"journal of mechanics of materials and structures":0.9,
"journal of membrane science":8.4,
"journal of membrane science letters":4.9,
"journal of metals materials and minerals":0.7,
"journal of microencapsulation":3,
"journal of micro-nanopatterning materials and metrology-jm3":1.5,
"journal of microwave power and electromagnetic energy":0.9,
"journal of molecular and engineering materials":2.4,
"journal of molecular modeling":2.1,
"journal of mountain science":0.43,
"journal of nano research":0.8,
"journal of nanobiotechnology":10.6,
"journal of nanoparticle research":2.1,
"journal of nanostructure in chemistry":8.6,
"journal of natural gas science and engineering":4.9,
"journal of neuroinflammation":9.3,
"journal of new materials for electrochemical systems":0.7,
"journal of new technology and materials":0.8,
"journal of non-crystalline solids":3.2,
"journal of nondestructive evaluation":2.6,
"journal of nondestructive evaluation, diagnostics and prognostics of engineering systems":2,
"journal of nuclear materials":2.9,
"journal of nuclear medicine":9.1,
"journal of occupational and environmental hygiene":0.42,
"journal of ocean engineering and science":13,
"journal of optoelectronic and biomedical materials":0.9,
"journal of optoelectronics and advanced materials":0.6,
"journal of oral science":1.9,
"journal of ovonic research":0.9,
"journal of paleolimnology":0.48,
"journal of pharmaceutical sciences":3.7,
"journal of phase equilibria and diffusion":1.5,
"journal of photochemistry and photobiology c-photochemistry reviews":12.8,
"journal of photonics for energy":1.5,
"journal of photopolymer science and technology":0.4,
"journal of physical and chemical reference data":4.4,
"journal of physical chemistry c":3.3,
"journal of physical chemistry letters":4.8,
"journal of physics and chemistry of solids":4.3,
"journal of physics-energy":7.1,
"journal of physics-materials":4.9,
"journal of physiotherapy":9.7,
"journal of plastic film & sheeting":2.1,
"journal of political ecology":0.44,
"journal of polymer & composites":0.1,
"journal of polymer engineering":1.7,
"journal of polymer materials":0.3,
"journal of polymer research":2.6,
"journal of polymer science":3.9,
"journal of polymers and the environment":4.7,
"journal of porous materials":2.5,
"journal of porphyrins and phthalocyanines":0.9,
"journal of power sources":8.1,
"journal of power sources advances":5.4,
"journal of process control":3.3,
"journal of product innovation management":10.1,
"journal of radiological protection":0.45,
"journal of regional science":0.7,
"journal of reinforced plastics and composites":2.3,
"journal of remote sensing":1.3,
"journal of research in interactive marketing":9.6,
"journal of retailing and consumer services":11,
"journal of rock mechanics and geotechnical engineering":9.4,
"journal of rubber research":1.2,
"journal of sandwich structures & materials":3.5,
"journal of saudi chemical society":5.8,
"journal of science-advanced materials and devices":6.7,
"journal of sedimentary environments":0.24,
"journal of service research":9.8,
"journal of siberian federal university-chemistry":0.5,
"journal of soil science and plant nutrition":0.83,
"journal of soils and sediments":0.68,
"journal of sport and health science":9.7,
"journal of strain analysis for engineering design":1.5,
"journal of sulfur chemistry":2.1,
"journal of supercritical fluids":3.4,
"journal of superhard materials":1.2,
"journal of supply chain management":10.2,
"journal of surfactants and detergents":1.6,
"journal of sustainable cement-based materials":4.7,
"journal of sustainable development of energy water and environment systems-jsdewes":0.49,
"journal of terramechanics":0.25,
"journal of testing and evaluation":0.9,
"journal of the academy of marketing science":9.5,
"journal of the air & waste management association":0.36,
"journal of the american academy of child and adolescent psychiatry":9.2,
"journal of the american academy of dermatology":12.8,
"journal of the american chemical society":14.4,
"journal of the american college of cardiology":21.7,
"journal of the american society of nephrology":10.3,
"journal of the american water resources association":0.46,
"journal of the association of environmental and resource economists":0.93,
"journal of the brazilian chemical society":1.3,
"journal of the chemical society of pakistan":0.6,
"journal of the chilean chemical society":1.6,
"journal of the chinese chemical society":1.6,
"journal of the electrochemical society":3.1,
"journal of the indian chemical society":3.2,
"journal of the indian society of remote sensing":0.42,
"journal of the iranian chemical society":2.2,
"journal of the korean chemical society-daehan hwahak hoe jee":0.3,
"journal of the korean society for nondestructive testing":0.4,
"journal of the mechanical behavior of biomedical materials":3.4,
"journal of the mechanical behavior of materials":1.7,
"journal of the mechanics and physics of solids":5,
"journal of the mexican chemical society":1.1,
"journal of the national comprehensive cancer network":14.8,
"journal of the pakistan institute of chemical engineers":0.1,
"journal of the serbian chemical society":1,
"journal of the society for information display":1.7,
"journal of the taiwan institute of chemical engineers":5.5,
"journal of thermal spray technology":3.2,
"journal of thermoplastic composite materials":3.6,
"journal of thoracic oncology":21,
"journal of toxicology and environmental health-part a-current issues":0.71,
"journal of toxicology and environmental health-part b-critical reviews":0.78,
"journal of travel medicine":9.1,
"journal of vacuum science & technology a":2.4,
"journal of vinyl & additive technology":3.8,
"journal of water and health":0.56,
"journal of water process engineering":6.3,
"journal of wood chemistry and technology":1.7,
"journal of wood science":2.2,
"journal of wuhan university of technology-materials science edition":1.3,
"kagaku kogaku ronbunshu":0.3,
"kemija u industriji-journal of chemists and chemical engineers":0.6,
"kgk-kautschuk gummi kunststoffe":0.4,
"kidney international":14.8,
"kidney international supplements":19.3,
"kona powder and particle journal":2.6,
"korea-australia rheology journal":2.2,
"korean chemical engineering research":0.5,
"korean journal of chemical engineering":2.9,
"korean journal of materials research":0.3,
"korean journal of metals and materials":1.1,
"kovove materialy-metallic materials":0.7,
"lab on a chip":6.1,
"lancet":98.4,
"lancet child & adolescent health":19.9,
"lancet diabetes & endocrinology":44,
"lancet digital health":23.8,
"lancet gastroenterology & hepatology":30.9,
"lancet global health":19.9,
"lancet haematology":15.4,
"lancet healthy longevity":13.4,
"lancet hiv":12.8,
"lancet infectious diseases":36.4,
"lancet microbe":20.9,
"lancet neurology":46.5,
"lancet oncology":41.6,
"lancet planetary health":24.1,
"lancet psychiatry":30.8,
"lancet public health":25.4,
"lancet regional health-europe":13.6,
"lancet respiratory medicine":38.7,
"lancet rheumatology":15,
"land":0.82,
"land degradation & development":0.84,
"land economics":0.44,
"land use policy":1.5,
"landscape and urban planning":2.37,
"landscape research":0.46,
"langmuir":3.7,
"laser & photonics reviews":9.8,
"lasers in engineering":0.6,
"latin american applied research":0.8,
"leadership quarterly":9.1,
"letras verdes":0.03,
"letters on materials":0.8,
"leukemia":12.8,
"light-science & applications":20.6,
"liquid crystals":2.4,
"liquid crystals reviews":4.8,
"liver cancer":11.6,
"living reviews in relativity":26.3,
"living reviews in solar physics":23,
"local environment":0.59,
"lubrication science":1.8,
"m+a-revista electronica de medio ambiente":0.05,
"macedonian journal of chemistry and chemical engineering":1.1,
"machining science and technology":2.7,
"macroheterocycles":1,
"macromolecular bioscience":4.4,
"macromolecular chemistry and physics":2.5,
"macromolecular materials and engineering":4.2,
"macromolecular rapid communications":4.2,
"macromolecular reaction engineering":1.8,
"macromolecular research":2.8,
"macromolecular theory and simulations":1.8,
"macromolecules":5.1,
"maderas-ciencia y tecnologia":1.2,
"magazine of concrete research":1.8,
"magnetic resonance in chemistry":1.9,
"magnetochemistry":2.6,
"main group chemistry":1.3,
"management of environmental quality":1.03,
"manufacturing letters":1.9,
"manufacturing technology":1.6,
"marine chemistry":3,
"marine environmental research":0.88,
"marine policy":1.46,
"marine pollution bulletin":1.49,
"marine resource economics":0.74,
"maritime studies":0.59,
"match-communications in mathematical and in computer chemistry":2.9,
"materiale plastice":0.6,
"materiales de construccion":1.1,
"materiali in tehnologije":0.6,
"materialia":3,
"materials":3.1,
"materials & design":7.7,
"materials advances":5.3,
"materials and corrosion-werkstoffe und korrosion":1.6,
"materials and manufacturing processes":4.1,
"materials and structures":3.4,
"materials at high temperatures":1,
"materials characterization":4.9,
"materials chemistry and physics":4.3,
"materials chemistry frontiers":6,
"materials evaluation":0.5,
"materials for quantum technology":3.1,
"materials for renewable and sustainable energy":3.6,
"materials futures":12,
"materials horizons":12.2,
"materials letters":2.7,
"materials letters-x":2.2,
"materials performance and characterization":0.6,
"materials physics and mechanics":0.6,
"materials research bulletin":5.3,
"materials research express":1.8,
"materials research letters":8.7,
"materials research-ibero-american journal of materials":1.5,
"materials science":0.7,
"materials science & engineering c-materials for biological applications":8.1,
"materials science & engineering r-reports":31.6,
"materials science and engineering a-structural materials properties microstructure and processing":6.2,
"materials science and engineering b-advanced functional solid-state materials":3.9,
"materials science and technology":1.7,
"materials science in semiconductor processing":4.3,
"materials science-medziagotyra":0.8,
"materials science-poland":1.3,
"materials technology":2.9,
"materials testing":2.5,
"materials today":21.1,
"materials today advances":8.1,
"materials today bio":9,
"materials today chemistry":6.7,
"materials today communications":3.7,
"materials today energy":9.1,
"materials today nano":8.2,
"materials today physics":10,
"materials today sustainability":7.2,
"materials transactions":1.2,
"materialwissenschaft und werkstofftechnik":1.2,
"materia-rio de janeiro":0.5,
"materiaux & techniques":1.3,
"mathematics and mechanics of solids":1.8,
"matter":17.3,
"mechanics of advanced materials and structures":3.7,
"mechanics of composite materials":1.5,
"mechanics of materials":3.4,
"mechanics of time-dependent materials":2.2,
"med":12.8,
"medcomm":10.7,
"medical image analysis":10.7,
"medicinal research reviews":10.9,
"membrane and water treatment":0.8,
"membranes":3.3,
"membranes and membrane technologies":2,
"mendeleev communications":1.8,
"metabolism-clinical and experimental":10.8,
"metallurgical and materials transactions a-physical metallurgy and materials science":2.2,
"metallurgical and materials transactions b-process metallurgy and materials processing science":2.4,
"metals":2.6,
"metals and materials international":3.3,
"micro & nano letters":1.5,
"micro and nano engineering":2.8,
"microbial risk analysis":0.75,
"microbiome":13.8,
"microelectronics international":0.7,
"microporous and mesoporous materials":4.8,
"microscopy and microanalysis":2.9,
"microsystem technologies-micro-and nanosystems-information storage and processing systems":1.6,
"military medical research":16.7,
"minerals engineering":4.9,
"mires and peat":0.23,
"mitigation and adaptation strategies for global change":0.59,
"mmwr surveillance summaries":37.3,
"mmwr-morbidity and mortality weekly report":25.4,
"modeling earth systems and environment":0.51,
"modelling and simulation in materials science and engineering":1.9,
"mokuzai gakkaishi":0.1,
"molecular biology and evolution":11,
"molecular cancer":27.7,
"molecular cell":14.5,
"molecular crystals and liquid crystals":0.7,
"molecular diversity":3.9,
"molecular horticulture":10.6,
"molecular neurodegeneration":14.9,
"molecular plant":17.1,
"molecular psychiatry":9.6,
"molecular systems design & engineering":3.2,
"molecular therapy":12.1,
"molecules":4.2,
"monatshefte fur chemie":1.7,
"monographs of the society for research in child development":9.4,
"moroccan journal of chemistry":2.4,
"moscow university chemistry bulletin":0.7,
"mountain research and development":0.32,
"mrs advances":0.8,
"mrs bulletin":4.1,
"mrs communications":1.8,
"multidiscipline modeling in materials and structures":1.7,
"multiscale and multidisciplinary modeling experiments and design":1.9,
"mycosphere":10,
"nano":1,
"nano convergence":13.4,
"nano energy":16.8,
"nano express":2.7,
"nano futures":2.5,
"nano letters":9.6,
"nano life":0.8,
"nano materials science":12.6,
"nano research":9.5,
"nano today":13.2,
"nanocomposites":4.2,
"nanoimpact":0.78,
"nanomaterials":4.4,
"nanomaterials and energy":0.3,
"nanomaterials and nanotechnology":3.1,
"nano-micro letters":31.6,
"nanophotonics":6.5,
"nanoscale":5.8,
"nanoscale advances":4.6,
"nanoscale and microscale thermophysical engineering":2.8,
"nanoscale horizons":8,
"nanoscale research letters":5.5,
"nanotechnology":2.9,
"nanotechnology and precision engineering":3.5,
"nanotechnology reviews":6.1,
"national science review":16.3,
"natural hazards review":0.57,
"natural product reports":10.2,
"natural resource modeling":0.41,
"natural resources forum":0.75,
"natural resources journal":0.37,
"nature":50.5,
"nature + culture":0.13,
"nature aging":17,
"nature astronomy":12.9,
"nature biomedical engineering":26.8,
"nature biotechnology":33.1,
"nature cancer":23.5,
"nature cardiovascular research":9.4,
"nature catalysis":42.8,
"nature cell biology":17.3,
"nature chemical biology":12.9,
"nature chemistry":19.2,
"nature climate change":29.6,
"nature communications":14.7,
"nature computational science":12,
"nature ecology & evolution":13.9,
"nature electronics":33.7,
"nature energy":49.7,
"nature food":23.6,
"nature genetics":31.7,
"nature geoscience":15.7,
"nature human behaviour":21.4,
"nature immunology":27.7,
"nature machine intelligence":18.8,
"nature materials":37.2,
"nature medicine":58.7,
"nature metabolism":18.9,
"nature methods":36.1,
"nature microbiology":20.5,
"nature nanotechnology":38.1,
"nature neuroscience":21.2,
"nature photonics":32.3,
"nature physics":17.6,
"nature plants":15.8,
"nature protocols":13.1,
"nature reviews cancer":72.5,
"nature reviews cardiology":41.7,
"nature reviews chemistry":38.1,
"nature reviews clinical oncology":81.1,
"nature reviews disease primers":76.9,
"nature reviews drug discovery":122.7,
"nature reviews earth & environment":49.7,
"nature reviews endocrinology":31,
"nature reviews gastroenterology & hepatology":45.9,
"nature reviews genetics":39.1,
"nature reviews immunology":67.7,
"nature reviews materials":79.8,
"nature reviews methods primers":50.1,
"nature reviews microbiology":69.2,
"nature reviews molecular cell biology":81.3,
"nature reviews nephrology":28.6,
"nature reviews neurology":28.2,
"nature reviews neuroscience":28.7,
"nature reviews physics":44.8,
"nature reviews psychology":16.8,
"nature reviews rheumatology":29.4,
"nature reviews urology":12.1,
"nature structural & molecular biology":12.5,
"nature sustainability":25.7,
"ndt & e international":4.2,
"neuron":14.7,
"neuro-oncology":16.4,
"new astronomy reviews":11.7,
"new carbon materials":6.5,
"new england journal of medicine":96.2,
"new journal of chemistry":2.7,
"new materials compounds and applications":0.6,
"nihon reoroji gakkaishi":1.3,
"nitrogen":0.29,
"nondestructive testing and evaluation":3.1,
"nordic pulp & paper research journal":0.9,
"npg asia materials":8.6,
"npj 2d materials and applications":9.1,
"npj clean water":10.4,
"npj computational materials":9.4,
"npj digital medicine":12.4,
"npj flexible electronics":12.3,
"npj materials degradation":6.7,
"npj quantum materials":5.5,
"npj urban sustainability":9.1,
"nucleic acids research":16.6,
"observatorio medioambiental":0.04,
"ocean yearbook":0.12,
"ochrona przed korozja":0.2,
"oil & gas science and technology-revue d ifp energies nouvelles":1.8,
"one earth":15.1,
"one ecosystem":0.4,
"open chemistry":2.1,
"open house international":0.99,
"ophthalmology":13.1,
"opir materialiv i teoria sporud-strength of materials and theory of structures":0.2,
"optical materials":3.9,
"optical materials express":2.8,
"opto-electronic advances":15.3,
"optoelectronics and advanced materials-rapid communications":0.5,
"orbital-the electronic journal of chemistry":0.7,
"organic electronics":2.7,
"organization & environment":1.01,
"oriental journal of chemistry":0.3,
"ovidius university annals of chemistry":1,
"oxford open materials science":2.9,
"ozone-science & engineering":0.32,
"papers in regional science":0.58,
"particle & particle systems characterization":2.7,
"particulate science and technology":2.3,
"particuology":4.1,
"pastoralism-research policy and practice":0.42,
"periodica polytechnica-chemical engineering":1.4,
"periodico tche quimica":0.2,
"periodontology 2000":17.5,
"persoonia":9.5,
"perspectives on psychological science":10.5,
"petroleum":4.2,
"petroleum chemistry":1.3,
"petroleum science and technology":1.3,
"pharmaceutical research":3.5,
"pharmacological research":9.1,
"pharmacological reviews":19.3,
"pharmacology & therapeutics":12,
"pharmazie":1.5,
"philosophical magazine":1.5,
"philosophical magazine letters":1.2,
"photonics and nanostructures-fundamentals and applications":2.6,
"photonix":15.7,
"physica status solidi a-applications and materials science":1.9,
"physica status solidi-rapid research letters":2.5,
"physical chemistry research":1.4,
"physical geography":0.32,
"physical mesomechanics":1.8,
"physical review b":3.2,
"physical review materials":3.1,
"physical review x":11.6,
"physics and chemistry of minerals":1.3,
"physics and chemistry of solid state":0.9,
"physics of life reviews":13.7,
"physics reports-review section of physics letters":23.9,
"physiological reviews":29.9,
"pigment & resin technology":1.3,
"plant biotechnology journal":10.1,
"plant cell":10,
"plant communications":9.4,
"plasma chemistry and plasma processing":2.6,
"plasma processes and polymers":2.9,
"plasmonics":3.3,
"plastics rubber and composites":2.1,
"plos medicine":10.5,
"polar journal":0.39,
"polar record":0.3,
"polimeros-ciencia e tecnologia":1,
"polimery":1.1,
"polish journal of chemical technology":0.7,
"polish journal of environmental studies":0.31,
"pollution":0.27,
"polymer":4.1,
"polymer bulletin":3.1,
"polymer chemistry":4.1,
"polymer composites":4.8,
"polymer crystallization":1.9,
"polymer degradation and stability":6.3,
"polymer engineering and science":3.2,
"polymer international":2.9,
"polymer journal":2.3,
"polymer reviews":11.1,
"polymer science series a":1,
"polymer science series b":1,
"polymer science series c":1.6,
"polymer testing":5,
"polymer-korea":0.4,
"polymer-plastics technology and materials":2.6,
"polymers":4.7,
"polymers & polymer composites":2.1,
"polymers for advanced technologies":3.1,
"polysaccharides":4.7,
"population and environment":1.06,
"powder diffraction":0.3,
"powder technology":4.5,
"problemy ekorozwoju":0.28,
"proceedings of the combustion institute":5.3,
"proceedings of the ieee":23.2,
"proceedings of the institution of civil engineers-waste and resource management":0.12,
"proceedings of the institution of mechanical engineers part l-journal of materials-design and applications":2.5,
"proceedings of the national academy of sciences of the united states of america":9.4,
"process biochemistry":3.7,
"process integration and optimization for sustainability":2.1,
"process safety and environmental protection":6.9,
"process safety progress":1,
"processes":2.8,
"processes of petrochemistry and oil refining":0.2,
"production engineering archives":1.9,
"progress in additive manufacturing":4.4,
"progress in aerospace sciences":11.5,
"progress in biomaterials":4.4,
"progress in chemistry":1,
"progress in crystal growth and characterization of materials":4.5,
"progress in disaster science":1.11,
"progress in energy":11.5,
"progress in energy and combustion science":32,
"progress in lipid research":14,
"progress in materials science":33.6,
"progress in natural science-materials international":4.8,
"progress in organic coatings":6.5,
"progress in particle and nuclear physics":14.5,
"progress in photovoltaics":8,
"progress in planning":1.23,
"progress in polymer science":26,
"progress in retinal and eye research":18.6,
"progress in rubber plastics and recycling technology":1.1,
"progress on chemistry and application of chitin and its derivatives":0.8,
"propellants explosives pyrotechnics":1.7,
"prosthesis":2.8,
"protein & cell":13.6,
"prx quantum":9.3,
"przemysl chemiczny":0.3,
"psychological bulletin":17.3,
"psychological science in the public interest":18.2,
"psychotherapy and psychosomatics":16.3,
"psyecology-bilingual journal of environmental psychology-revista bilingue de psicologia ambiental":0.27,
"pulmonology":10.4,
"pulp & paper-canada":0.4,
"pure and applied chemistry":2,
"qualitative psychology":11.7,
"quantitative infrared thermography journal":3.8,
"quantum beam science":1.3,
"quarterly journal of economics":11.1,
"quimica nova":0.5,
"radiation and environmental biophysics":0.41,
"radiation protection dosimetry":0.25,
"radiologia medica":9.7,
"radiology":12.1,
"radioprotection":0.55,
"rangeland ecology & management":0.57,
"rapid prototyping journal":3.4,
"rare metal materials and engineering":0.6,
"rare metals":9.6,
"reaction chemistry & engineering":3.4,
"reactions":2.2,
"reactive & functional polymers":4.5,
"recent patents on nanotechnology":2,
"redox biology":10.7,
"regenerative biomaterials":5.6,
"regional environmental change":0.75,
"regional science and urban economics":0.95,
"regional studies":1.04,
"regional sustainability":0.83,
"reliability engineering & system safety":9.4,
"remediation-the journal of environmental cleanup costs technologies & techniques":0.26,
"remote sensing":0.97,
"remote sensing applications-society and environment":0.82,
"remote sensing of environment":11.1,
"renewable & sustainable energy reviews":16.3,
"reports on progress in physics":19,
"research in nondestructive evaluation":1.1,
"research on chemical intermediates":2.8,
"resource and energy economics":0.62,
"resources conservation & recycling advances":1.05,
"resources conservation and recycling":11.2,
"resources environment and sustainability":12.4,
"resources policy":2.59,
"resources-basel":0.56,
"results in chemistry":2.5,
"results in physics":4.4,
"review of environmental economics and policy":1.82,
"review of european comparative & international environmental law":1.56,
"reviews in chemical engineering":4.9,
"reviews in environmental science and bio-technology":1.1,
"reviews of environmental contamination and toxicology":0.78,
"reviews of geophysics":25.2,
"reviews of modern physics":45.9,
"reviews on advanced materials science":3.6,
"reviews on environmental health":0.4,
"revista brasileira de ciencias ambientais":0.1,
"revista colombiana de quimica":0.2,
"revista de estudios regionales":0.02,
"revista de gestao ambiental e sustentabilidade-geas":0.05,
"revista de sociedad gaditana de historia natural":0.01,
"revista eletronica em gestao educacao e tecnologia ambiental":0.03,
"revista habitat sustentable":0.04,
"revista internacional de contaminacion ambiental":0.07,
"revista mexicana de ingenieria quimica":1,
"revista romana de materiale-romanian journal of materials":0.4,
"revista virtual de quimica":0.4,
"revue des composites et des materiaux avances-journal of composite and advanced materials":1,
"revue roumaine de chimie":0.4,
"river research and applications":0.41,
"road materials and pavement design":3.4,
"robotics and computer-integrated manufacturing":9.1,
"rocznik ochrona srodowiska":0.07,
"rsc advances":3.9,
"rsc chemical biology":4.2,
"rubber chemistry and technology":1.2,
"russian chemical bulletin":1.7,
"russian chemical reviews":7,
"russian journal of general chemistry":0.9,
"russian journal of nondestructive testing":1,
"sains tanah":0.13,
"sampe journal":0.2,
"sar and qsar in environmental research":2.3,
"science":44.7,
"science advances":11.7,
"science and engineering of composite materials":1.5,
"science and public policy":0.68,
"science and technology for energy transition":1.5,
"science and technology of advanced materials":7.4,
"science and technology of energetic materials":0.4,
"science and technology of welding and joining":3.1,
"science bulletin":18.8,
"science china-chemistry":10.4,
"science china-materials":7,
"science china-technological sciences":4.4,
"science immunology":17.6,
"science of remote sensing":1.31,
"science of the total environment":1.62,
"science robotics":26.1,
"science translational medicine":15.8,
"scientific study and research-chemistry and chemical engineering biotechnology food industry":0.3,
"scripta materialia":5.3,
"semiconductor science and technology":1.9,
"seminars in cancer biology":12.1,
"sensors and materials":1,
"separation and purification reviews":5.2,
"separation and purification technology":8.1,
"separation science and technology":2.3,
"shape memory and superelasticity":2.6,
"siam review":10.8,
"signal transduction and targeted therapy":40.8,
"silicon":2.8,
"sleep medicine reviews":11.2,
"small":13,
"small methods":10.7,
"small science":11.1,
"small structures":13.9,
"smart materials and structures":3.7,
"smartmat":15.3,
"society & natural resources":0.65,
"soft materials":1.6,
"soft matter":2.9,
"soil & sediment contamination":0.31,
"soil biology & biochemistry":9.8,
"soil science and plant nutrition":0.36,
"solar energy materials and solar cells":6.3,
"solar rrl":6.1,
"soldering & surface mount technology":1.7,
"solid fuel chemistry":0.8,
"solids":2.4,
"solvent extraction and ion exchange":1.8,
"solvent extraction research and development-japan":0.6,
"south african journal of chemistry-suid-afrikaanse tydskrif vir chemie":0.8,
"sports medicine":9.3,
"statistics surveys":11,
"steel and composite structures":4.1,
"stochastic environmental research and risk assessment":1.07,
"strain":1.9,
"strength fracture and complexity":0.4,
"strength of materials":0.8,
"structural chemistry":2.1,
"studia universitatis babes-bolyai chemia":0.5,
"studies in mycology":14.1,
"supramolecular chemistry":2.1,
"surface & coatings technology":5.3,
"surface coatings international":0.1,
"surface engineering":2.4,
"surface innovations":2.7,
"surface topography-metrology and properties":2,
"surfaces":2.3,
"surfaces and interfaces":5.7,
"susmat":18.7,
"sustainability":0.68,
"sustainability accounting management and policy journal":1.2,
"sustainability science":0.94,
"sustainability-science practice and policy":1.06,
"sustainable chemistry and pharmacy":5.5,
"sustainable cities and society":10.5,
"sustainable development":9.9,
"sustainable energy & fuels":5,
"sustainable environment":0.33,
"sustainable environment research":0.75,
"sustainable futures":0.69,
"sustainable materials and technologies":8.6,
"sustainable production and consumption":10.9,
"synthetic metals":4,
"tappi journal":0.6,
"technological forecasting and social change":12.9,
"technology in society":10.1,
"technovation":11.1,
"tenside surfactants detergents":1.2,
"theoretical and experimental chemistry":0.7,
"theoretical foundations of chemical engineering":0.7,
"theranostics":12.4,
"thin solid films":2,
"tissue engineering part a":3.5,
"tissue engineering part b-reviews":5.1,
"tissue engineering part c-methods":2.7,
"topics in current chemistry":7.1,
"tourism management":10.9,
"toxicological and environmental chemistry":0.29,
"toxicology and environmental health sciences":0.34,
"toxics":0.84,
"trac-trends in analytical chemistry":11.8,
"transactions of famena":1.4,
"transactions of the institute of metal finishing":1.2,
"transactions of tianjin university":6.7,
"transactions on electrical and electronic materials":1.6,
"translational neurodegeneration":10.8,
"transnational environmental law":2.8,
"transport in porous media":2.7,
"transport reviews":9.5,
"transportation research part d-transport and environment":1.63,
"trends in biochemical sciences":11.6,
"trends in biotechnology":14.3,
"trends in cancer":14.3,
"trends in cell biology":13,
"trends in chemistry":14,
"trends in cognitive sciences":16.7,
"trends in ecology & evolution":16.7,
"trends in endocrinology and metabolism":11.4,
"trends in environmental analytical chemistry":11.1,
"trends in food science & technology":15.1,
"trends in genetics":13.6,
"trends in immunology":13.1,
"trends in microbiology":14,
"trends in molecular medicine":12.8,
"trends in neurosciences":14.6,
"trends in pharmacological sciences":13.9,
"trends in plant science":17.3,
"tribology letters":2.9,
"tribology-materials surfaces & interfaces":1.6,
"trumpeter-journal of ecosophy":0,
"tungsten":5.6,
"turkish journal of chemistry":1.3,
"ultrasonics sonochemistry":8.7,
"university politehnica of bucharest scientific bulletin series b-chemistry and materials science":0.3,
"urban climate":1.34,
"urban forestry & urban greening":1.76,
"urban policy and research":0.5,
"urban science":0.59,
"urban studies":1.11,
"uspekhi fiziki metallov-progress in physics of metals":1.5,
"utilities policy":0.7,
"vacuum":3.8,
"vadose zone journal":0.6,
"vietnam journal of chemistry":1.3,
"view":9.7,
"virtual and physical prototyping":10.2,
"waste and biomass valorization":0.53,
"waste disposal & sustainable energy":0.45,
"waste management":1.13,
"waste management & research":0.45,
"water":0.67,
"water air and soil pollution":0.57,
"water alternatives-an interdisciplinary journal on water politics and development":0.56,
"water and environment journal":0.45,
"water biology and security":1.2,
"water conservation science and engineering":0.25,
"water economics and policy":0.31,
"water environment research":0.52,
"water research":11.4,
"water research x":1.18,
"water resources and economics":0.62,
"water resources research":1.22,
"water reuse":0.76,
"water science and technology":0.43,
"water supply":0.33,
"wear":5.3,
"weather climate and society":0.45,
"web ecology":0.52,
"wetlands":0.42,
"wetlands ecology and management":0.39,
"wiley interdisciplinary reviews-climate change":9.4,
"wiley interdisciplinary reviews-computational molecular science":16.8,
"wiley interdisciplinary reviews-water":1.07,
"wochenblatt fur papierfabrikation":0.1,
"wood and fiber science":0.8,
"wood material science & engineering":2.2,
"wood research":0.9,
"wood science and technology":3.1,
"world psychiatry":60.5,
"zkg international":0.2
}

var fieldName = "series";
var newValue = "";

var fieldID = Zotero.ItemFields.getID(fieldName);
var s = new Zotero.Search();
s.libraryID = ZoteroPane.getSelectedLibraryID();
var ids = await s.search();
if (!ids.length) {
return "No items found";
}
await Zotero.DB.executeTransaction(async function () {
for (let id of ids) {
let item = await Zotero.Items.getAsync(id);
let mappedFieldID = Zotero.ItemFields.getFieldIDFromTypeAndBase(item.itemTypeID, fieldName);
var IF=impact_factors[item.getField('publicationTitle').toLowerCase()]
item.setField(mappedFieldID ? mappedFieldID : fieldID, newValue);
if(IF!=undefined){
    item.setField('series',IF)
}

await item.save();
}
});
return ids.length + " item(s) IF updated, and shown in series field!";
